const DSA_DATA = {
  topics: [
    {
      id: "arrays-strings",
      title: "Arrays & Strings",
      icon: "▦",
      subtopics: [
        {
          id: "two-pointers",
          title: "Two Pointers",
          description:
            "Two indices moving toward each other or in the same direction to avoid nested loops.",
          problems: [
            {
              id: "tp1",
              title: "Two Sum II – Input Array Is Sorted",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
              day: 1,
              hint: "Array is sorted + find two numbers that sum to target → two pointers from both ends. If sum too small, move left pointer right. If too big, move right pointer left.",
              trigger: "sorted array + pair sum",
            },
            {
              id: "tp2",
              title: "Valid Palindrome",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/valid-palindrome/",
              day: 1,
              hint: "Compare characters from both ends moving inward. Skip non-alphanumeric. If they ever differ → not palindrome.",
              trigger: "check from both ends",
            },
            {
              id: "tp3",
              title: "Container With Most Water",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/container-with-most-water/",
              day: 2,
              hint: "Start with widest container. Always move the shorter line inward — there's no point keeping the shorter one since width only decreases.",
              trigger: "maximize area + two boundaries",
            },
            {
              id: "tp4",
              title: "3Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/3sum/",
              day: 2,
              hint: "Sort first. Fix one number, then use two pointers on the rest. Skip duplicates explicitly to avoid repeated triplets.",
              trigger: "sorted + three numbers summing to zero",
            },
            {
              id: "tp5",
              title: "Remove Duplicates from Sorted Array",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
              day: 3,
              hint: "Slow pointer marks where next unique goes. Fast pointer scans ahead. When fast finds a new value, copy it to slow's position.",
              trigger: "in-place modification + sorted + two speeds",
            },
            {
              id: "tp6",
              title: "Squares of a Sorted Array",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/squares-of-a-sorted-array/",
              day: 3,
              hint: "Largest squares come from either end (most negative or most positive). Fill result array from the back, always picking the larger square.",
              trigger: "sorted array + compare from both ends",
            },
            {
              id: "tp7",
              title: "Trapping Rain Water",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/trapping-rain-water/",
              day: 4,
              hint: "Water at any index = min(maxLeft, maxRight) - height[i]. Use two pointers: process the side with the smaller max, because that's the limiting factor.",
              trigger: "bounded by left and right walls + two pointers",
            },
            {
              id: "tp8",
              title: "Sort Colors (Dutch Flag)",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/sort-colors/",
              day: 4,
              hint: "Three pointers: low (0s boundary), mid (current), high (2s boundary). Swap and advance based on what mid points to.",
              trigger: "three-way partition + in-place",
            },
            {
              id: "tp9",
              title: "Move Zeroes",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/move-zeroes/",
              day: 5,
              hint: "Slow pointer marks where next non-zero goes. Fast pointer scans. Swap when fast finds a non-zero.",
              trigger: "in-place + maintain relative order + two speeds",
            },
            {
              id: "tp10",
              title: "4Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/4sum/",
              day: 5,
              hint: "Sort. Fix two outer numbers with nested loops, then use two pointers on the remaining part. Skip duplicates at each level.",
              trigger: "sorted + k-sum pattern + nested two pointers",
            },
            {
              id: "tp11",
              title: "Minimum Size Subarray Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/minimum-size-subarray-sum/",
              day: 5,
              hint: "Two pointers forming a window. Expand right adding elements. When sum >= target, try shrinking from left to minimize window. Record minimum length.",
              trigger: "minimum length + contiguous + sum >= target",
            },
            {
              id: "tp12",
              title: "Boats to Save People",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/boats-to-save-people/",
              day: 6,
              hint: "Sort people by weight. Try to pair heaviest with lightest. If they fit, both board. If not, heaviest goes alone. Left and right pointers.",
              trigger: "pair heaviest with lightest + greedy + two pointers",
            },
          ],
        },
        {
          id: "sliding-window",
          title: "Sliding Window",
          description:
            "A window over contiguous elements that expands/shrinks based on a validity condition.",
          problems: [
            {
              id: "sw1",
              title: "Best Time to Buy and Sell Stock",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
              day: 7,
              hint: "Track minimum price seen so far (left pointer). Current profit = price - min. Keep updating max profit.",
              trigger: "contiguous days + maximize difference",
            },
            {
              id: "sw2",
              title: "Longest Substring Without Repeating Characters",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
              day: 7,
              hint: "Expand right, add char to set. If duplicate found, shrink from left until the duplicate is removed. Window is always valid.",
              trigger: "longest + contiguous + no repeat constraint",
            },
            {
              id: "sw3",
              title: "Longest Repeating Character Replacement",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-repeating-character-replacement/",
              day: 8,
              hint: "Window size - count of most frequent char = replacements needed. If > k, shrink left. Key insight: you only need to track max frequency seen (never decrease it).",
              trigger: "longest + at most k replacements + window validity",
            },
            {
              id: "sw4",
              title: "Permutation in String",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/permutation-in-string/",
              day: 8,
              hint: "Fixed window of size len(s1). Compare frequency maps. Slide window across s2, adding right char and removing left char each step.",
              trigger: "fixed window size + frequency match",
            },
            {
              id: "sw5",
              title: "Minimum Window Substring",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/minimum-window-substring/",
              day: 9,
              hint: "Expand right until all chars covered. Then shrink left as much as possible while still covering all chars. Record minimum each time valid.",
              trigger: "shortest + contains all chars + variable window",
            },
            {
              id: "sw6",
              title: "Sliding Window Maximum",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/sliding-window-maximum/",
              day: 9,
              hint: "Use a deque storing indices in decreasing order of values. Front of deque is always the max. Remove elements outside window from front. Remove smaller elements from back.",
              trigger: "fixed window + max in window + efficient update",
            },
            {
              id: "sw7",
              title: "Fruit Into Baskets",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/fruit-into-baskets/",
              day: 10,
              hint: "Exactly 'longest subarray with at most 2 distinct values'. Variable window — expand right, if distinct types > 2, shrink from left.",
              trigger: "longest + at most k distinct + variable window",
            },
            {
              id: "sw8",
              title: "Max Consecutive Ones III",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/max-consecutive-ones-iii/",
              day: 10,
              hint: "Window can contain at most k zeros. Expand right freely. When zeros in window exceed k, shrink from left. Window length at the end is the answer.",
              trigger: "longest + at most k of something allowed",
            },
            {
              id: "sw9",
              title: "Subarray Product Less Than K",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/subarray-product-less-than-k/",
              day: 10,
              hint: "Expand right multiplying. If product >= k, shrink left dividing. For each right position, number of valid subarrays ending here = right - left + 1.",
              trigger: "count subarrays + product constraint + variable window",
            },
            {
              id: "sw10",
              title: "Longest Subarray of 1s After Deleting One Element",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/",
              day: 11,
              hint: "Sliding window with at most one 0 allowed. Track zero count. When zeros > 1, shrink left. Answer is window size - 1 (for the deleted element).",
              trigger:
                "delete exactly one + longest 1s + at most one zero window",
            },
          ],
        },
        {
          id: "prefix-sum",
          title: "Prefix Sum & Hashing",
          description:
            "Precompute cumulative sums or use hash maps to answer range queries in O(1).",
          problems: [
            {
              id: "ps1",
              title: "Subarray Sum Equals K",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/subarray-sum-equals-k/",
              day: 12,
              hint: "prefix[j] - prefix[i] = k means prefix[i] = prefix[j] - k. Store prefix sums in a map as you go. At each index, check if (currentSum - k) was seen before.",
              trigger: "subarray sum = k + count subarrays",
            },
            {
              id: "ps2",
              title: "Product of Array Except Self",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/product-of-array-except-self/",
              day: 12,
              hint: "For each index: product of all left elements × product of all right elements. Do two passes — left prefix products first, then multiply in right suffix products.",
              trigger: "prefix + suffix product passes",
            },
            {
              id: "ps3",
              title: "Continuous Subarray Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/continuous-subarray-sum/",
              day: 13,
              hint: "If two prefix sums have the same remainder mod k, the subarray between them sums to a multiple of k. Store {remainder: index} in map. Check if current remainder was seen at least 2 indices ago.",
              trigger: "subarray sum multiple of k + prefix mod",
            },
            {
              id: "ps4",
              title: "Range Sum Query – Immutable",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/range-sum-query-immutable/",
              day: 13,
              hint: "Build prefix sum array once. sumRange(i,j) = prefix[j+1] - prefix[i]. O(1) per query.",
              trigger: "multiple range queries + precomputation",
            },
            {
              id: "ps5",
              title: "Longest Consecutive Sequence",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-consecutive-sequence/",
              day: 14,
              hint: "Put all numbers in a hash set. For each number n, only start counting if n-1 is NOT in the set (it's a sequence start). Then count how long the streak extends.",
              trigger: "O(n) + check existence + hash set",
            },
            {
              id: "ps6",
              title: "Two Sum",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/two-sum/",
              day: 14,
              hint: "For each number, check if (target - number) already exists in the map. If yes, found the pair. If no, add current number to map.",
              trigger: "complement exists + O(1) lookup + hash map",
            },
            {
              id: "ps7",
              title: "Find Pivot Index",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/find-pivot-index/",
              day: 14,
              hint: "Precompute total sum. Iterate left to right tracking leftSum. RightSum = total - leftSum - nums[i]. If leftSum == rightSum, found pivot.",
              trigger: "equal left and right sum + prefix sum",
            },
            {
              id: "ps8",
              title: "Contiguous Array",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/contiguous-array/",
              day: 15,
              hint: "Replace 0s with -1. Now find longest subarray with sum = 0. Use prefix sum trick — if same prefix sum seen before, subarray between them has sum 0.",
              trigger: "equal 0s and 1s + transform + prefix sum",
            },
          ],
        },
        {
          id: "kadane",
          title: "Kadane's / Array DP",
          description:
            "Track running optimum — extend or restart at each element.",
          problems: [
            {
              id: "k1",
              title: "Maximum Subarray",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/maximum-subarray/",
              day: 16,
              hint: "At each index: extend previous subarray OR start fresh from current element. curr = max(curr + num, num). If extending makes it worse than just num alone, restart.",
              trigger: "maximum sum + contiguous + extend or restart",
            },
            {
              id: "k2",
              title: "Maximum Product Subarray",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/maximum-product-subarray/",
              day: 16,
              hint: "Track both max AND min product ending here (negative × negative = positive). At each step: maxProd = max(num, maxPrev*num, minPrev*num).",
              trigger:
                "maximum product + negatives can flip + track both extremes",
            },
            {
              id: "k3",
              title: "Jump Game",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/jump-game/",
              day: 17,
              hint: "Track the furthest index reachable so far. At each index, if index > furthest reachable, you can't get here. Otherwise update furthest = max(furthest, i + nums[i]).",
              trigger: "can you reach the end + greedy furthest reach",
            },
            {
              id: "k4",
              title: "Maximum Sum Circular Subarray",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/maximum-sum-circular-subarray/",
              day: 17,
              hint: "Answer is either: (1) max subarray not wrapping (standard Kadane), or (2) totalSum - minSubarray (the wrap-around case). Take the max of both.",
              trigger: "circular + max subarray + wrap-around case",
            },
            {
              id: "k5",
              title: "Jump Game II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/jump-game-ii/",
              day: 18,
              hint: "Greedy BFS-like. Track current level's farthest reach and next level's farthest reach. Increment jumps when you exhaust current level's range.",
              trigger: "minimum jumps + greedy level by level",
            },
            {
              id: "k6",
              title: "Best Time to Buy and Sell Stock II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
              day: 18,
              hint: "Collect every upward slope: if prices[i] > prices[i-1], add the difference. This is equivalent to making optimal trades every day.",
              trigger: "multiple transactions + greedy + accumulate gains",
            },
          ],
        },
      ],
    },
    {
      id: "linked-lists",
      title: "Linked Lists",
      icon: "⬡",
      subtopics: [
        {
          id: "fast-slow",
          title: "Fast & Slow Pointers",
          description:
            "Two pointers at different speeds to detect cycles, find midpoints.",
          problems: [
            {
              id: "fs1",
              title: "Linked List Cycle",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/linked-list-cycle/",
              day: 19,
              hint: "Fast moves 2 steps, slow moves 1. If there's a cycle, fast will eventually lap slow and they'll meet. If fast reaches null, no cycle.",
              trigger: "cycle detection + two speeds",
            },
            {
              id: "fs2",
              title: "Find the Duplicate Number",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/find-the-duplicate-number/",
              day: 19,
              hint: "Treat array values as 'next pointers'. The duplicate creates a cycle. Use Floyd's algorithm: find meeting point, then find cycle entry (start fresh pointer from head).",
              trigger: "duplicate creates cycle + Floyd's algorithm",
            },
            {
              id: "fs3",
              title: "Middle of the Linked List",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/middle-of-the-linked-list/",
              day: 20,
              hint: "When fast reaches the end (or null), slow is at the middle. Fast moves 2, slow moves 1.",
              trigger: "find middle in one pass + two speeds",
            },
            {
              id: "fs4",
              title: "Linked List Cycle II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/linked-list-cycle-ii/",
              day: 20,
              hint: "After fast and slow meet inside cycle, reset one pointer to head. Move both one step at a time. They meet at the cycle entry point.",
              trigger: "find cycle entry + Floyd's two-phase algorithm",
            },
            {
              id: "fs5",
              title: "Happy Number",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/happy-number/",
              day: 20,
              hint: "Repeatedly squaring digits either reaches 1 or cycles. Use fast/slow to detect cycle. If slow == 1, happy. If slow == fast (cycle), not happy.",
              trigger: "infinite loop detection + fast/slow on number sequence",
            },
            {
              id: "fs6",
              title: "Palindrome Linked List",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/palindrome-linked-list/",
              day: 21,
              hint: "Find middle with fast/slow. Reverse second half. Compare first half with reversed second half node by node.",
              trigger: "fast/slow to find middle + reverse half + compare",
            },
          ],
        },
        {
          id: "reversal",
          title: "In-place Reversal",
          description:
            "Reverse a list or part of it using pointer manipulation.",
          problems: [
            {
              id: "r1",
              title: "Reverse Linked List",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/reverse-linked-list/",
              day: 22,
              hint: "Three pointers: prev (null), curr (head), next (temp). For each node: save next, point curr.next to prev, advance prev and curr.",
              trigger: "reverse order + pointer rerouting",
            },
            {
              id: "r2",
              title: "Reverse Linked List II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/reverse-linked-list-ii/",
              day: 22,
              hint: "Use dummy node. Find the node just before position left. Reverse the sublist from left to right using the standard reversal. Reconnect the ends.",
              trigger: "reverse sublist + reconnect segments",
            },
            {
              id: "r3",
              title: "Reorder List",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/reorder-list/",
              day: 23,
              hint: "Three steps: (1) find middle, (2) reverse second half, (3) merge the two halves alternately.",
              trigger: "interleave first and last + three-step approach",
            },
            {
              id: "r4",
              title: "Remove Nth Node From End of List",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
              day: 23,
              hint: "Two pointers with a gap of n. Advance fast pointer n steps first. Then move both until fast reaches the end. Slow is now at the node before the one to remove.",
              trigger: "nth from end + two pointers with fixed gap",
            },
            {
              id: "r5",
              title: "Merge Two Sorted Lists",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/merge-two-sorted-lists/",
              day: 24,
              hint: "Use a dummy head. Compare heads of both lists, attach the smaller one to result, advance that list's pointer. Attach remaining list at the end.",
              trigger: "merge sorted + dummy head + compare and advance",
            },
            {
              id: "r6",
              title: "Swap Nodes in Pairs",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/swap-nodes-in-pairs/",
              day: 24,
              hint: "Use dummy head. For each pair: save second, point first to second.next, point second to first, attach pair to previous node. Advance two steps.",
              trigger: "swap adjacent pairs + pointer rerouting + dummy head",
            },
            {
              id: "r7",
              title: "Reverse Nodes in k-Group",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/reverse-nodes-in-k-group/",
              day: 24,
              hint: "Check if k nodes remain. If yes, reverse that group. Recurse on remainder. Connect reversed group to recursed result.",
              trigger: "reverse k at a time + check count first + recurse",
            },
          ],
        },
      ],
    },
    {
      id: "stacks-queues",
      title: "Stacks & Queues",
      icon: "⊟",
      subtopics: [
        {
          id: "monotonic-stack",
          title: "Monotonic Stack",
          description:
            "A stack that maintains elements in increasing or decreasing order to solve next greater/smaller element problems.",
          problems: [
            {
              id: "ms1",
              title: "Valid Parentheses",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/valid-parentheses/",
              day: 25,
              hint: "Push open brackets onto stack. For closing brackets, check if top of stack is the matching opener. If stack is empty at end, valid.",
              trigger: "matching pairs + LIFO + stack",
            },
            {
              id: "ms2",
              title: "Daily Temperatures",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/daily-temperatures/",
              day: 25,
              hint: "Monotonic decreasing stack of indices. For each temp, pop all indices with smaller temps — they found their warmer day. Distance = current index - popped index.",
              trigger:
                "next greater element + distance to it + monotonic stack",
            },
            {
              id: "ms3",
              title: "Next Greater Element I",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/next-greater-element-i/",
              day: 25,
              hint: "Process nums2 with monotonic stack. When popping (found a greater element), record the mapping. Look up each nums1 element in the map.",
              trigger: "next greater + lookup + monotonic stack + hashmap",
            },
            {
              id: "ms4",
              title: "Car Fleet",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/car-fleet/",
              day: 26,
              hint: "Sort by position descending. Compute time to reach target for each car. If current car's time <= previous fleet's time, it joins that fleet (pop nothing). Otherwise it starts a new fleet.",
              trigger: "merging groups + time comparison + stack-like thinking",
            },
            {
              id: "ms5",
              title: "Largest Rectangle in Histogram",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
              day: 26,
              hint: "Monotonic increasing stack of indices. When you find a shorter bar, pop and compute area: height[popped] × (current - stack.top - 1). Add sentinel 0 at end.",
              trigger: "widest rectangle bounded by height + monotonic stack",
            },
            {
              id: "ms6",
              title: "Asteroid Collision",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/asteroid-collision/",
              day: 26,
              hint: "Stack simulates surviving asteroids. Positive asteroids always push. Negative asteroids: pop positive ones smaller than |negative|. Equal → both destroyed.",
              trigger: "collision simulation + stack + opposing directions",
            },
            {
              id: "ms7",
              title: "Remove K Digits",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/remove-k-digits/",
              day: 27,
              hint: "Monotonic increasing stack. For each digit, while stack top > current digit and k > 0, pop (that removes a larger digit, making number smaller). Build result from stack.",
              trigger: "remove digits to minimize number + monotonic stack",
            },
            {
              id: "ms8",
              title: "132 Pattern",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/132-pattern/",
              day: 27,
              hint: "Traverse right to left. Stack maintains candidates for the '2' (middle value). k tracks the maximum 'popped' value as the '3'. When you find nums[i] < k, 132 pattern exists.",
              trigger:
                "three elements with specific order + monotonic stack + traverse backwards",
            },
          ],
        },
        {
          id: "queue-deque",
          title: "Queue / Deque Patterns",
          description:
            "Use queues for BFS simulation and deques for O(1) max/min queries over a sliding window.",
          problems: [
            {
              id: "qd1",
              title: "Implement Queue using Stacks",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/implement-queue-using-stacks/",
              day: 28,
              hint: "Two stacks: inbox and outbox. Push to inbox. For pop/peek, if outbox empty, transfer all from inbox to outbox (reversal makes FIFO). Amortized O(1).",
              trigger: "FIFO from LIFO + two stacks + amortized",
            },
            {
              id: "qd2",
              title: "Implement Stack using Queues",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/implement-stack-using-queues/",
              day: 28,
              hint: "One queue. After pushing a new element, rotate the queue (size-1) times so the new element is at the front. Now pop/peek just use queue's front.",
              trigger: "LIFO from FIFO + rotation trick",
            },
            {
              id: "qd3",
              title: "Design Circular Queue",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/design-circular-queue/",
              day: 28,
              hint: "Array of fixed size with head and tail pointers. Wrap around with modulo. Track size to differentiate full vs empty.",
              trigger: "circular buffer + modulo wrapping + fixed capacity",
            },
            {
              id: "qd4",
              title: "Design Hit Counter",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/design-hit-counter/",
              day: 29,
              hint: "Queue storing timestamps. On hit, push timestamp. On getHits, pop all timestamps older than (current - 300). Return queue size.",
              trigger: "sliding time window + queue + expire old entries",
            },
            {
              id: "qd5",
              title: "Task Scheduler",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/task-scheduler/",
              day: 29,
              hint: "Most frequent task determines idle slots. Formula: (maxFreq - 1) * (n + 1) + count of tasks with maxFreq. Take max with total tasks.",
              trigger:
                "cooldown period + most frequent task + formula or simulation",
            },
            {
              id: "qd6",
              title: "Max Stack",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/max-stack/",
              day: 29,
              hint: "Two stacks: main and maxStack. maxStack mirrors main but each entry is the max so far. On pop, pop both. O(1) max query.",
              trigger: "O(1) max + push/pop + two parallel stacks",
            },
          ],
        },
        {
          id: "stack-design",
          title: "Stack-based Problems",
          description:
            "Classic problems where a stack elegantly captures the 'most recent relevant state'.",
          problems: [
            {
              id: "sd1",
              title: "Min Stack",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/min-stack/",
              day: 30,
              hint: "Maintain a second stack that stores the minimum at each level. When pushing x, push min(x, minStack.top) to minStack. Pop both together.",
              trigger: "O(1) min query + push/pop + auxiliary stack",
            },
            {
              id: "sd2",
              title: "Evaluate Reverse Polish Notation",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
              day: 30,
              hint: "Push numbers onto stack. When you see an operator, pop two numbers, apply operator, push result. Final answer is the only element left.",
              trigger:
                "postfix evaluation + operands wait on stack + operator triggers pop",
            },
            {
              id: "sd3",
              title: "Decode String",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/decode-string/",
              day: 30,
              hint: "Stack stores (current_string, multiplier) pairs. On '[', push current state. On ']', pop and repeat. Handles nested brackets naturally.",
              trigger: "nested repetition + remember context + stack",
            },
            {
              id: "sd4",
              title: "Basic Calculator II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/basic-calculator-ii/",
              day: 31,
              hint: "Process one number at a time. For + and -, push to stack. For * and /, pop top and compute with current number, push result. Sum the stack at end.",
              trigger: "operator precedence + defer addition + stack",
            },
            {
              id: "sd5",
              title: "Number of Visible People in a Queue",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/number-of-visible-people-in-a-queue/",
              day: 31,
              hint: "Traverse right to left. Monotonic decreasing stack. For each person, count how many shorter people are visible until a taller one blocks. The taller one is also visible.",
              trigger:
                "visibility + taller person blocks shorter ones + monotonic stack",
            },
          ],
        },
      ],
    },
    {
      id: "trees",
      title: "Trees",
      icon: "⌥",
      subtopics: [
        {
          id: "tree-dfs",
          title: "Tree DFS",
          description:
            "Depth-first traversal for path problems, structure checks, and subtree queries.",
          problems: [
            {
              id: "td1",
              title: "Maximum Depth of Binary Tree",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
              day: 32,
              hint: "Return 0 for null. For any node: depth = 1 + max(dfs(left), dfs(right)). The recursion naturally explores all paths.",
              trigger: "tree depth + recurse and combine",
            },
            {
              id: "td2",
              title: "Diameter of Binary Tree",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/diameter-of-binary-tree/",
              day: 32,
              hint: "Diameter through a node = depth(left) + depth(right). For each node compute this and update global max. Return depth (not diameter) up to parent.",
              trigger: "path through node = left depth + right depth",
            },
            {
              id: "td3",
              title: "Path Sum",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/path-sum/",
              day: 33,
              hint: "Pass remaining sum down. At a leaf, check if remaining == leaf value. Recurse into both children with (remaining - node.val).",
              trigger: "root-to-leaf path + pass remaining sum",
            },
            {
              id: "td4",
              title: "Binary Tree Maximum Path Sum",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
              day: 33,
              hint: "At each node: max path through it = node.val + max(0, leftGain) + max(0, rightGain). But return only node.val + max one side (since path can't branch when returning to parent).",
              trigger: "path through node + can't go both ways when returning",
            },
            {
              id: "td5",
              title: "Lowest Common Ancestor of BST",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
              day: 34,
              hint: "In BST: if both p and q are less than root, go left. If both greater, go right. Otherwise current node is the LCA.",
              trigger: "BST properties + branch point = LCA",
            },
            {
              id: "td6",
              title: "Validate Binary Search Tree",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/validate-binary-search-tree/",
              day: 34,
              hint: "Pass valid range [min, max] down. Every node must be strictly within its range. Left child gets (min, node.val) and right child gets (node.val, max).",
              trigger: "BST validity + pass bounds down recursively",
            },
            {
              id: "td7",
              title: "Symmetric Tree",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/symmetric-tree/",
              day: 34,
              hint: "Mirror check: isMirror(left, right). Base cases: both null → true, one null → false, values differ → false. Recurse: isMirror(left.left, right.right) && isMirror(left.right, right.left).",
              trigger: "mirror structure + compare opposing subtrees",
            },
            {
              id: "td8",
              title: "Count Good Nodes in Binary Tree",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
              day: 35,
              hint: "Pass max value seen on path from root. Node is 'good' if its value >= max. Recurse with updated max.",
              trigger: "path maximum + compare with current node + DFS",
            },
          ],
        },
        {
          id: "tree-bfs",
          title: "Tree BFS / Level Order",
          description: "Process a tree level by level using a queue.",
          problems: [
            {
              id: "tb1",
              title: "Binary Tree Level Order Traversal",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
              day: 36,
              hint: "Queue-based BFS. At each level, record queue size first. Process exactly that many nodes, then add their children. This separates levels cleanly.",
              trigger: "level by level + queue + process current level size",
            },
            {
              id: "tb2",
              title: "Binary Tree Right Side View",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/binary-tree-right-side-view/",
              day: 36,
              hint: "Level order BFS. The last node processed at each level is visible from the right side.",
              trigger: "last node per level + BFS",
            },
            {
              id: "tb3",
              title: "Minimum Depth of Binary Tree",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/minimum-depth-of-binary-tree/",
              day: 36,
              hint: "BFS naturally finds shortest path first. The first leaf node you encounter in BFS is the shallowest one.",
              trigger: "minimum depth + BFS finds minimum first",
            },
            {
              id: "tb4",
              title: "Average of Levels in Binary Tree",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/average-of-levels-in-binary-tree/",
              day: 37,
              hint: "BFS level order. For each level, sum all node values, divide by level size. Standard BFS level-separator technique.",
              trigger: "per-level aggregate + BFS level order",
            },
            {
              id: "tb5",
              title: "Zigzag Level Order Traversal",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/",
              day: 37,
              hint: "BFS level order but alternate direction. Use a flag: even levels go left-to-right, odd levels go right-to-left (just reverse the level array).",
              trigger: "alternating direction per level + BFS + toggle flag",
            },
          ],
        },
      ],
    },
    {
      id: "graphs",
      title: "Graphs",
      icon: "◈",
      subtopics: [
        {
          id: "graph-bfs",
          title: "Graph BFS",
          description:
            "Shortest path in unweighted graphs. BFS always guarantees minimum steps.",
          problems: [
            {
              id: "gb1",
              title: "Number of Islands",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/number-of-islands/",
              day: 38,
              hint: "For each unvisited '1', do a BFS/DFS to mark the entire island as visited, increment count. Each BFS call = one island.",
              trigger: "connected components + count regions",
            },
            {
              id: "gb2",
              title: "Rotting Oranges",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/rotting-oranges/",
              day: 38,
              hint: "Multi-source BFS: add ALL rotten oranges to queue at start. BFS spreads rot level by level. Each level = 1 minute. Check if fresh remain at end.",
              trigger:
                "minimum time + spread from multiple sources + BFS levels",
            },
            {
              id: "gb3",
              title: "Word Ladder",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/word-ladder/",
              day: 39,
              hint: "BFS where each word is a node. Neighbors = words differing by one letter. BFS level = transformation steps. First time you reach endWord = shortest path.",
              trigger: "minimum steps + one change at a time + BFS",
            },
            {
              id: "gb4",
              title: "01 Matrix",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/01-matrix/",
              day: 39,
              hint: "Multi-source BFS from all 0s simultaneously. Distance of each 1 = BFS level when it's first reached. Don't BFS from each 1 separately (too slow).",
              trigger: "distance to nearest 0 + multi-source BFS",
            },
            {
              id: "gb5",
              title: "Shortest Path in Binary Matrix",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/shortest-path-in-binary-matrix/",
              day: 39,
              hint: "BFS from (0,0) to (n-1,n-1). Move in 8 directions. Mark visited immediately when enqueuing, not when dequeuing. Level = path length.",
              trigger: "shortest path on grid + 8 directions + BFS",
            },
          ],
        },
        {
          id: "graph-dfs",
          title: "Graph DFS & Topological Sort",
          description:
            "Connectivity, cycle detection, ordering with dependencies.",
          problems: [
            {
              id: "gd1",
              title: "Course Schedule",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/course-schedule/",
              day: 40,
              hint: "Build a directed graph of prerequisites. Can finish all courses iff the graph has no cycle. Use DFS with three states: unvisited, visiting (in current path), visited.",
              trigger: "dependencies + can complete all + cycle detection",
            },
            {
              id: "gd2",
              title: "Course Schedule II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/course-schedule-ii/",
              day: 40,
              hint: "Topological sort (Kahn's algorithm with BFS or DFS postorder). Process nodes with 0 in-degree first. Result order = valid course order.",
              trigger: "ordering with dependencies + topological sort",
            },
            {
              id: "gd3",
              title: "Pacific Atlantic Water Flow",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
              day: 41,
              hint: "Reverse the problem: BFS/DFS inward from ocean borders. Mark which cells can reach Pacific, which can reach Atlantic. Answer = intersection.",
              trigger: "reverse direction + two separate reachability sets",
            },
            {
              id: "gd4",
              title: "Clone Graph",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/clone-graph/",
              day: 41,
              hint: "DFS with a hash map: {original node → cloned node}. Before recursing into a neighbor, check if it's already cloned. This handles cycles.",
              trigger: "deep copy + cycle-safe + map original to clone",
            },
            {
              id: "gd5",
              title: "Redundant Connection",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/redundant-connection/",
              day: 42,
              hint: "Union-Find. Process edges one by one. If both endpoints already in same component, this edge creates a cycle — it's redundant.",
              trigger: "cycle in undirected graph + union find",
            },
            {
              id: "gd6",
              title: "Number of Connected Components in Undirected Graph",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
              day: 42,
              hint: "Union-Find or DFS. For each unvisited node, DFS marks all reachable nodes as one component. Count how many times you start a fresh DFS.",
              trigger: "count separate groups + union find or DFS",
            },
          ],
        },
      ],
    },
    {
      id: "dp",
      title: "Dynamic Programming",
      icon: "◫",
      subtopics: [
        {
          id: "dp-1d",
          title: "1D Dynamic Programming",
          description:
            "State depends on one variable. Build answer from smaller subproblems.",
          problems: [
            {
              id: "dp1",
              title: "Climbing Stairs",
              difficulty: "Easy",
              platform: "leetcode",
              link: "https://leetcode.com/problems/climbing-stairs/",
              day: 43,
              hint: "dp[i] = ways to reach step i = dp[i-1] + dp[i-2]. You can come from one step below or two steps below. Fibonacci in disguise.",
              trigger: "number of ways + each step depends on previous two",
            },
            {
              id: "dp2",
              title: "House Robber",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/house-robber/",
              day: 43,
              hint: "dp[i] = max money robbing up to house i = max(dp[i-1], dp[i-2] + nums[i]). At each house: skip it OR rob it (can't rob adjacent).",
              trigger: "choose or skip + can't pick adjacent + 1D DP",
            },
            {
              id: "dp3",
              title: "Coin Change",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/coin-change/",
              day: 44,
              hint: "dp[amount] = min coins to make amount. For each coin, dp[i] = min(dp[i], dp[i-coin] + 1). Initialize dp[0]=0, rest as infinity.",
              trigger: "minimum coins + unbounded choices + build up to target",
            },
            {
              id: "dp4",
              title: "Word Break",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/word-break/",
              day: 44,
              hint: "dp[i] = can we segment s[0..i-1]. For each position j < i, if dp[j] is true AND s[j..i-1] is in dict, then dp[i] = true.",
              trigger: "can you partition + check all split points + 1D DP",
            },
            {
              id: "dp5",
              title: "Decode Ways",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/decode-ways/",
              day: 45,
              hint: "dp[i] = ways to decode s[0..i-1]. Check single digit (s[i-1] != '0') and two digits (10-26). Handle '0' carefully — it can't stand alone.",
              trigger: "count ways to decode + single or double digit choices",
            },
            {
              id: "dp6",
              title: "House Robber II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/house-robber-ii/",
              day: 45,
              hint: "Circular means first and last can't both be robbed. Run House Robber I twice: once on [0..n-2], once on [1..n-1]. Take the max.",
              trigger: "circular + can't rob both ends + run twice",
            },
            {
              id: "dp7",
              title: "Longest Increasing Subsequence",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-increasing-subsequence/",
              day: 46,
              hint: "dp[i] = LIS ending at index i. For each i, check all j < i where nums[j] < nums[i]: dp[i] = max(dp[i], dp[j]+1). O(n²) DP or O(n log n) with patience sort.",
              trigger:
                "subsequence + each element extends some previous + 1D DP",
            },
            {
              id: "dp8",
              title: "Partition Equal Subset Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/partition-equal-subset-sum/",
              day: 46,
              hint: "Can we find a subset summing to totalSum/2? 1D knapsack: dp[j] = can we make sum j. For each num, iterate j from target down to num: dp[j] |= dp[j-num].",
              trigger: "subset sum + knapsack boolean DP",
            },
          ],
        },
        {
          id: "dp-2d",
          title: "2D Dynamic Programming",
          description:
            "State depends on two variables — two strings, grid position, or item+capacity.",
          problems: [
            {
              id: "d2d1",
              title: "Unique Paths",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/unique-paths/",
              day: 47,
              hint: "dp[i][j] = paths to reach cell (i,j) = dp[i-1][j] + dp[i][j-1]. Can only come from above or from left.",
              trigger: "grid + count paths + can only move right/down",
            },
            {
              id: "d2d2",
              title: "Longest Common Subsequence",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/longest-common-subsequence/",
              day: 47,
              hint: "dp[i][j] = LCS of text1[0..i-1] and text2[0..j-1]. If chars match: dp[i][j] = dp[i-1][j-1] + 1. Else: max(dp[i-1][j], dp[i][j-1]).",
              trigger: "two strings + longest common + 2D DP table",
            },
            {
              id: "d2d3",
              title: "Edit Distance",
              difficulty: "Hard",
              platform: "leetcode",
              link: "https://leetcode.com/problems/edit-distance/",
              day: 48,
              hint: "dp[i][j] = min edits to convert word1[0..i] to word2[0..j]. If chars match: dp[i-1][j-1]. Else: 1 + min(insert, delete, replace) from 3 neighbors.",
              trigger: "transform one string to another + 3 operations + 2D DP",
            },
            {
              id: "d2d4",
              title: "Coin Change II",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/coin-change-ii/",
              day: 48,
              hint: "dp[i][j] = ways to make amount j using first i coins. Either skip coin i: dp[i-1][j], or use it: dp[i][j-coin]. Outer loop: coins, inner: amounts.",
              trigger: "count ways + items with reuse + 0/1 knapsack variant",
            },
            {
              id: "d2d5",
              title: "Minimum Path Sum",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/minimum-path-sum/",
              day: 49,
              hint: "dp[i][j] = minimum sum to reach (i,j). dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1]). Initialize first row and column separately.",
              trigger: "grid + minimum cost path + right and down only",
            },
            {
              id: "d2d6",
              title: "Maximal Square",
              difficulty: "Medium",
              platform: "leetcode",
              link: "https://leetcode.com/problems/maximal-square/",
              day: 49,
              hint: "dp[i][j] = side of largest square with bottom-right at (i,j). If cell is '1': dp[i][j] = min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) + 1.",
              trigger:
                "largest square of 1s + depends on three neighbors + 2D DP",
            },
          ],
        },
      ],
    },
  ],

  leetcode: {
    competitions: {
      schedule: "Every Sunday 8:00 AM IST (Weekly) & Sat 8:00 PM (Biweekly)",
      tip: "LeetCode contests test raw pattern recognition. Q1 is usually brute force, Q2/Q3 are maps/DP/graphs. Q4 is advanced math or segment trees.",
      links: {
        upcoming: "https://leetcode.com/contest/",
        problemset: "https://leetcode.com/problemset/all/",
        edu: "https://leetcode.com/explore/",
      },
    },
    topics: [
      {
        id: "lc-top-150",
        title: "Top Interview 150",
        icon: "❖",
        description:
          "The absolute must-do problems for any standard tech or FAANG interview.",
        subtopics: [
          {
            id: "lc-array-string",
            title: "Array / String",
            description:
              "Core manipulation, fast/slow pointers, and greedy logic.",
            problems: [
              {
                id: "lc1",
                title: "Merge Sorted Array",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/merge-sorted-array/",
                tags: ["Array", "Two Pointers"],
                hint: "Start filling the array from the back to avoid overwriting elements you still need.",
                trigger: "in-place merge + sorted",
              },
              {
                id: "lc2",
                title: "Remove Element",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/remove-element/",
                tags: ["Array", "Two Pointers"],
                hint: "Use a slow pointer for the position of the next non-target element.",
                trigger: "in-place modification + keep order",
              },
              {
                id: "lc3",
                title: "Remove Duplicates from Sorted Array",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/",
                tags: ["Array", "Two Pointers"],
                hint: "Compare current element with the previous one. If different, move slow pointer and copy.",
                trigger: "sorted + unique items + in-place",
              },
              {
                id: "lc4",
                title: "Majority Element",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/majority-element/",
                tags: ["Array", "Divide and Conquer"],
                hint: "Boyer-Moore Voting Algorithm. Track a candidate and a count. If count hits 0, swap candidate.",
                trigger: "element > n/2 + O(1) space",
              },
              {
                id: "lc5",
                title: "Rotate Array",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/rotate-array/",
                tags: ["Array", "Math"],
                hint: "Reverse the whole array, then reverse the first k elements, then reverse the rest.",
                trigger: "rotate in-place O(1) space",
              },
              {
                id: "lc6",
                title: "Best Time to Buy and Sell Stock",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
                tags: ["Array", "DP"],
                hint: "Keep track of the minimum price seen so far and continuously update the maximum profit.",
                trigger: "maximize single transaction profit",
              },
              {
                id: "lc7",
                title: "Jump Game",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/jump-game/",
                tags: ["Greedy", "Array"],
                hint: "Keep track of the furthest index you can reach. If you reach an index > furthest, you lose.",
                trigger: "can you reach the end + jump lengths",
              },
            ],
          },
          {
            id: "lc-hashmap",
            title: "Hashmap",
            description:
              "O(1) lookups to optimize O(N^2) brute force solutions.",
            problems: [
              {
                id: "lc8",
                title: "Ransom Note",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/ransom-note/",
                tags: ["Hash Table", "String"],
                hint: "Count frequencies of letters in the magazine, subtract when reading the ransom note.",
                trigger: "can construct string A from string B",
              },
              {
                id: "lc9",
                title: "Isomorphic Strings",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/isomorphic-strings/",
                tags: ["Hash Table", "String"],
                hint: "Maintain two maps (s->t and t->s). Every character in s must map uniquely to a character in t and vice versa.",
                trigger: "1-to-1 character mapping",
              },
              {
                id: "lc10",
                title: "Word Pattern",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/word-pattern/",
                tags: ["Hash Table", "String"],
                hint: "Split string by spaces. Check 1-to-1 mapping between pattern characters and words. Similar to Isomorphic Strings.",
                trigger: "string pattern matches word sequence",
              },
              {
                id: "lc11",
                title: "Valid Anagram",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/valid-anagram/",
                tags: ["Hash Table", "String"],
                hint: "Count frequencies of both strings using a hash map or array of size 26. Compare.",
                trigger: "same characters + different order",
              },
              {
                id: "lc12",
                title: "Group Anagrams",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/group-anagrams/",
                tags: ["Hash Table", "String"],
                hint: "Sort each string and use it as a key in a hash map, or use a character count array as the key.",
                trigger: "grouping + anagrams",
              },
            ],
          },
        ],
      },
      {
        id: "lc-blind-75",
        title: "Blind 75",
        icon: "✦",
        description:
          "The classic curated list of the most frequent conceptual problems.",
        subtopics: [
          {
            id: "b75-arrays",
            title: "Arrays",
            description: "The core foundational array logic questions.",
            problems: [
              {
                id: "b75-1",
                title: "Two Sum",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/two-sum/",
                tags: ["Array", "Hash Table"],
                hint: "Store the complement (target - current) in a hash map as you iterate.",
                trigger: "pair sum + O(N) required",
              },
              {
                id: "b75-2",
                title: "Contains Duplicate",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/contains-duplicate/",
                tags: ["Array", "Hash Table"],
                hint: "Throw elements into a HashSet. If the size of the set != size of array, there's a duplicate.",
                trigger: "check any repeats + hash set",
              },
              {
                id: "b75-3",
                title: "Product of Array Except Self",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/product-of-array-except-self/",
                tags: ["Array", "Prefix Sum"],
                hint: "Calculate prefix products in one pass, then suffix products in a second reverse pass. Multiply them.",
                trigger: "exclude self + no division allowed",
              },
              {
                id: "b75-4",
                title: "Maximum Subarray",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/maximum-subarray/",
                tags: ["Array", "DP"],
                hint: "Kadane's Algorithm. Extend the current subarray or start a new one if the current sum becomes negative.",
                trigger: "largest contiguous sum",
              },
            ],
          },
          {
            id: "b75-dp",
            title: "Dynamic Programming",
            description: "Classic DP questions asked by almost everyone.",
            problems: [
              {
                id: "b75-5",
                title: "Climbing Stairs",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/climbing-stairs/",
                tags: ["DP", "Math"],
                hint: "Fibonacci sequence. dp[i] = dp[i-1] + dp[i-2].",
                trigger: "number of ways + 1 or 2 steps",
              },
              {
                id: "b75-6",
                title: "Coin Change",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/coin-change/",
                tags: ["DP", "BFS"],
                hint: "dp[amount] = min(dp[amount], dp[amount - coin] + 1). Initialize with infinity.",
                trigger: "minimum items to sum to target",
              },
              {
                id: "b75-7",
                title: "Longest Increasing Subsequence",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/longest-increasing-subsequence/",
                tags: ["DP", "Binary Search"],
                hint: "dp[i] is the LIS ending at index i. Compare with all previous smaller elements. O(N^2) or Patience Sort for O(N log N).",
                trigger: "strictly increasing + subsequence",
              },
            ],
          },
        ],
      },
      {
        id: "lc-striver",
        title: "Striver's SDE Sheet",
        icon: "◩",
        description:
          "Top 180+ problems for mastering Data Structures and Algorithms comprehensively.",
        subtopics: [
          {
            id: "sde-arrays-1",
            title: "Arrays Part-I",
            description: "Day 1 of Striver's SDE Sheet.",
            problems: [
              {
                id: "sde1",
                title: "Set Matrix Zeroes",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/set-matrix-zeroes/",
                tags: ["Array", "Matrix"],
                hint: "Use the first row and first column as markers to save O(M+N) space. Handle the intersection (0,0) carefully.",
                trigger: "propagate states across rows/cols + in-place",
              },
              {
                id: "sde2",
                title: "Pascal's Triangle",
                difficulty: "Easy",
                platform: "leetcode",
                link: "https://leetcode.com/problems/pascals-triangle/",
                tags: ["Array", "DP"],
                hint: "Each row starts and ends with 1. Inside elements are the sum of the two elements directly above it.",
                trigger: "generate combinations based on previous row",
              },
              {
                id: "sde3",
                title: "Next Permutation",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/next-permutation/",
                tags: ["Array", "Two Pointers"],
                hint: "Find first dip from right. Find smallest element greater than it to its right. Swap. Reverse everything after.",
                trigger: "lexicographically next arrangement",
              },
              {
                id: "sde4",
                title: "Sort Colors",
                difficulty: "Medium",
                platform: "leetcode",
                link: "https://leetcode.com/problems/sort-colors/",
                tags: ["Array", "Two Pointers", "Sorting"],
                hint: "Dutch National Flag algorithm. Pointers for 0s, 1s, and 2s.",
                trigger: "sort three unique values in one pass",
              },
            ],
          },
        ],
      },
    ],
  },

  codeforces: {
    competitions: {
      schedule: "Every Saturday at 7:35 PM IST (Codeforces Round, Div. 2)",
      tip: "Codeforces Div. 2 problems: A and B are easy-medium, C is medium, D/E are hard. As a beginner aim for A+B+C.",
      links: {
        upcoming: "https://codeforces.com/contests",
        problemset: "https://codeforces.com/problemset",
        edu: "https://codeforces.com/edu/courses",
      },
    },
    topics: [
      {
        id: "cf-basics",
        title: "Brute Force & Implementation",
        icon: "⬡",
        description:
          "The backbone of competitive programming. These problems teach you to think clearly and code precisely.",
        subtopics: [
          {
            id: "cf-impl",
            title: "Implementation / Simulation",
            description:
              "Simulate exactly what the problem says. No tricks — just careful coding.",
            problems: [
              {
                id: "cf1",
                title: "Watermelon",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/4/A",
                tags: ["Math", "Brute Force"],
                hint: "Can w be split into two even numbers? A number can be split into two even numbers iff it's even and greater than 2. Check both conditions.",
                trigger: "split into two even numbers",
              },
              {
                id: "cf2",
                title: "Way Too Long Words",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/71/A",
                tags: ["Strings", "Implementation"],
                hint: "If word length > 10, abbreviate to first_char + (len-2) + last_char. Otherwise keep as is.",
                trigger: "string abbreviation + conditional",
              },
              {
                id: "cf3",
                title: "Team",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/231/A",
                tags: ["Greedy", "Implementation"],
                hint: "For each problem, sum the votes from 3 people. If sum >= 2 (majority says yes), solve the problem. Count how many such problems.",
                trigger: "majority vote + count problems",
              },
              {
                id: "cf4",
                title: "Stones on the Table",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/266/A",
                tags: ["Implementation", "Strings"],
                hint: "Count removals: if current stone same color as previous stone on table, remove it (don't add). Count removals.",
                trigger: "remove adjacent duplicates + count",
              },
              {
                id: "cf5",
                title: "Next Round",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/158/A",
                tags: ["Implementation", "Greedy"],
                hint: "Find score of k-th participant. Count all participants whose score >= that threshold AND score > 0.",
                trigger: "threshold + count qualifiers",
              },
              {
                id: "cf6",
                title: "Bear and Prime 100",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/680/A",
                tags: ["Math", "Number Theory", "Interactive"],
                hint: "Query divisibility by all primes up to 100. If any prime divides the number, it's composite. Interactive problem — print your query and read the response.",
                trigger: "prime checking + query divisibility by small primes",
              },
              {
                id: "cf7",
                title: "Beautiful Matrix",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/339/A",
                tags: ["Implementation", "Greedy"],
                hint: "Count the zeros. There are 25 cells and the center must be 0, others 1. Find minimum swaps to put all zeros in right places.",
                trigger: "matrix transformation + swap counting",
              },
              {
                id: "cf8",
                title: "Soldier and Bananas",
                difficulty: "800",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/546/A",
                tags: ["Math", "Implementation"],
                hint: "First banana costs 1, second costs 2, ..., k-th costs k. Total = k*(k+1)/2. If you already have w coins, answer = max(0, total - w).",
                trigger: "triangular number + sum formula",
              },
            ],
          },
          {
            id: "cf-greedy",
            title: "Greedy Problems",
            description:
              "Make the locally optimal choice at each step. Prove it works by arguing no swap can improve it.",
            problems: [
              {
                id: "cf9",
                title: "Maximize the Profit",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1264/C",
                tags: ["Greedy", "Math"],
                hint: "Sort the gifts. Each 'buy one get one free' pair takes the two cheapest unpaired gifts. Process pairs from smallest to largest.",
                trigger: "pair items optimally + sort + greedy",
              },
              {
                id: "cf10",
                title: "Pangram",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/520/A",
                tags: ["Strings", "Implementation"],
                hint: "Count distinct lowercase letters in the string (convert to lowercase first). If all 26 present, it's a pangram.",
                trigger: "all 26 letters present + set or bitmask",
              },
              {
                id: "cf11",
                title: "Queue at the School",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/266/B",
                tags: ["Simulation", "Greedy"],
                hint: "Simulate t seconds. Each second: scan queue, boys and girls swap positions when a girl is directly in front of a boy. Simulate carefully.",
                trigger: "simulation + queue + multiple steps",
              },
              {
                id: "cf12",
                title: "Lucky Division",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/121/A",
                tags: ["Math", "Number Theory"],
                hint: "A lucky number only has digits 4 and 7. Generate all lucky numbers up to 10^7. For each n, check which lucky numbers divide it.",
                trigger: "enumerate special numbers + check divisibility",
              },
              {
                id: "cf13",
                title: "Vanya and Fence",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/677/A",
                tags: ["Greedy", "Implementation"],
                hint: "Process people one by one. If height > fence, need 2 columns. If <= fence, need 1 column. Sum up the width needed.",
                trigger: "conditional width + accumulate",
              },
              {
                id: "cf14",
                title: "Odd Divisor",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1475/C",
                tags: ["Math", "Number Theory"],
                hint: "A number has an odd divisor > 1 iff it is NOT a power of 2. Check if n is a power of 2 using n & (n-1) == 0 trick.",
                trigger: "odd divisor exists + power of 2 check",
              },
            ],
          },
        ],
      },
      {
        id: "cf-math",
        title: "Number Theory & Math",
        icon: "◎",
        description:
          "Math is the secret weapon of CP. These patterns appear constantly in Div.2 A/B/C problems.",
        subtopics: [
          {
            id: "cf-numtheory",
            title: "Divisibility & Primes",
            description:
              "GCD, prime factorization, sieve — the core tools of number theory.",
            problems: [
              {
                id: "cf15",
                title: "Anton and Danik",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/734/A",
                tags: ["Math", "Implementation"],
                hint: "Count who wins more games. If Anton wins more, output 'Anton'. If Danik wins more, output 'Danik'. Otherwise 'Friendship'.",
                trigger: "count and compare + simple conditional",
              },
              {
                id: "cf16",
                title: "Primes or Palindromes?",
                difficulty: "1300",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/568/A",
                tags: ["Math", "Brute Force"],
                hint: "Sieve for primes. Palindrome check for each number. Find the largest n ≤ some limit where primes/palindromes ratio >= p/q. Iterate from 1 upward.",
                trigger: "sieve + palindrome + iterate to find threshold",
              },
              {
                id: "cf17",
                title: "GCD Table",
                difficulty: "1300",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/583/B",
                tags: ["Math", "Number Theory", "Greedy"],
                hint: "Largest element in GCD table is always max of original array. Remove it. The second largest remaining that's a divisor of max is next element. Greedily reconstruct.",
                trigger: "GCD + reconstruct array + frequency counting",
              },
              {
                id: "cf18",
                title: "Interesting Drink",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/507/B",
                tags: ["Binary Search", "Math", "Implementation"],
                hint: "Sort prices. For each query m, binary search for how many prices are <= m. Answer = upper_bound index.",
                trigger: "count elements <= threshold + sort + binary search",
              },
              {
                id: "cf19",
                title: "Divisors",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/348/A",
                tags: ["Number Theory", "Math"],
                hint: "For each query: just iterate from 1 to sqrt(n), collecting divisors. For each i dividing n, add both i and n/i (avoid duplicates when i = sqrt(n)).",
                trigger: "find all divisors + iterate to sqrt + O(sqrt n)",
              },
              {
                id: "cf20",
                title: "Restore the Permutation",
                difficulty: "1300",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/959/B",
                tags: ["Greedy", "Implementation", "Math"],
                hint: "For each element a[i], greedily pick the largest unused number < a[i]. Use a sorted set or multiset. If at any point no valid number exists, print -1.",
                trigger:
                  "greedy selection + available numbers + strictly less than",
              },
            ],
          },
          {
            id: "cf-binsearch",
            title: "Binary Search",
            description:
              "Binary search on the answer — a technique for optimization problems where you verify feasibility.",
            problems: [
              {
                id: "cf21",
                title: "Toothpicks",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1033B",
                tags: ["Binary Search", "Math"],
                hint: "Binary search on the number of complete rows. For r rows: need r*(r+1)/2 + partial row toothpicks. Find largest r fitting in n.",
                trigger: "how many complete rows + binary search",
              },
              {
                id: "cf22",
                title: "Renting Bikes",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/363/C",
                tags: ["Binary Search", "Greedy", "Sorting"],
                hint: "Binary search on minimum money each person pays. For a given minimum payment x: sort bikes by price, see how many students can rent given budget constraints.",
                trigger: "binary search on answer + feasibility check",
              },
              {
                id: "cf23",
                title: "Find the Length of the Longest Common Prefix",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1873D",
                tags: ["Binary Search", "Hashing", "Strings"],
                hint: "Binary search on prefix length k. For each k, hash all prefixes of length k. Check if any hash appears in both strings.",
                trigger: "binary search on length + hash to verify",
              },
              {
                id: "cf24",
                title: "Ksenia and Array",
                difficulty: "1300",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/670C",
                tags: ["Binary Search", "Implementation"],
                hint: "Binary search on the answer. Check if it's possible to achieve target by simulating the operations.",
                trigger: "binary search on achievable value + simulation check",
              },
            ],
          },
        ],
      },
      {
        id: "cf-ds",
        title: "Data Structures",
        icon: "▦",
        description:
          "Efficient data structures to solve problems that brute force cannot handle.",
        subtopics: [
          {
            id: "cf-sorting",
            title: "Sorting & Searching",
            description:
              "Sort to unlock structure, then search efficiently. A fundamental CP pairing.",
            problems: [
              {
                id: "cf25",
                title: "Vasya and Socks",
                difficulty: "1000",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/460/B",
                tags: ["Math", "Simulation"],
                hint: "Simulate: each day use one pair. After every k days, add one sock. Track total socks. Stop when < 2.",
                trigger: "simulation + track inventory + replenish",
              },
              {
                id: "cf26",
                title: "Sherlock and his Girlfriend",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/776/B",
                tags: ["Greedy", "Sorting", "Implementation"],
                hint: "Sort numbers. Numbers >= sqrt(n) need 1 operation. Numbers < sqrt(n) need 2 operations. Just two colors needed (2-coloring). Assign color 1 to primes, color 2 to composites.",
                trigger: "color by type + sorting + two categories",
              },
              {
                id: "cf27",
                title: "Olya and Energy Drinks",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/877D",
                tags: ["Sorting", "Greedy"],
                hint: "Sort by energy. Greedily buy cheapest energy drinks first. Sum their volumes until total >= m.",
                trigger: "sort by cost + greedy minimum cost selection",
              },
              {
                id: "cf28",
                title: "Connecting Cities",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1433C",
                tags: ["Greedy", "Sorting", "Graphs"],
                hint: "Sort edges by cost. Use Union-Find. Add edges cheapest first. When two different components merge, count cost. Minimum spanning tree concept.",
                trigger: "MST + union find + sort edges",
              },
            ],
          },
          {
            id: "cf-prefix",
            title: "Prefix Sums & Difference Arrays",
            description:
              "Range queries and range updates in O(1) per operation after O(n) preprocessing.",
            problems: [
              {
                id: "cf29",
                title: "Berland Sequence",
                difficulty: "1100",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/768C",
                tags: ["Greedy", "Prefix Sums", "Implementation"],
                hint: "Simulate keeping a running sum. Whenever it becomes <= 0, add enough fuel (multiples of k) to make it 1. Track total added.",
                trigger: "running sum + add minimum to keep positive + greedy",
              },
              {
                id: "cf30",
                title: "Little Girl and Maximum Sum",
                difficulty: "1300",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/494/C",
                tags: ["Greedy", "Prefix Sums", "Sorting"],
                hint: "For each query [l,r], mark indices covered. Count how many times each index is queried (frequency array via difference array). Sort array and frequencies. Pair largest freq with largest element.",
                trigger: "difference array + frequency count + sort and pair",
              },
              {
                id: "cf31",
                title: "Xenia and Weights",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/342/C",
                tags: ["DFS", "Backtracking", "Implementation"],
                hint: "DFS/backtracking with constraints. Track which weights are used, and the difference on each scale. Prune branches that violate constraints.",
                trigger: "enumerate + prune with constraints + backtracking",
              },
              {
                id: "cf32",
                title: "Sereja and Brackets",
                difficulty: "1600",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/380/C",
                tags: ["Segment Tree", "Data Structures"],
                hint: "Segment tree where each node stores: max matched pairs, unmatched open brackets, unmatched close brackets. Merge intervals by matching closes with opens.",
                trigger: "range bracket matching + segment tree merge",
              },
            ],
          },
        ],
      },
      {
        id: "cf-graphs",
        title: "Graph Theory",
        icon: "◈",
        description:
          "Graph problems appear in almost every Codeforces round from Div. 2 C onwards.",
        subtopics: [
          {
            id: "cf-graph-basics",
            title: "BFS / DFS on Graphs",
            description:
              "The two fundamental graph traversal algorithms. Master these first.",
            problems: [
              {
                id: "cf33",
                title: "Vasya and Petya's Game",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/581/B",
                tags: ["Math", "Number Theory", "Games"],
                hint: "Factor n into prime factors. For each prime p, keep dividing n by p. Track how many times p divides n. The player who removes the last occurrence of a prime wins.",
                trigger: "prime factorization + game theory + factor tracking",
              },
              {
                id: "cf34",
                title: "Journey",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1000C",
                tags: ["DFS", "Trees", "Recursion"],
                hint: "DFS on tree. At each node, decide to go left or right (can go straight as well). Track time spent. If time budget runs out exactly at a leaf = win.",
                trigger: "tree DFS + time constraint + path finding",
              },
              {
                id: "cf35",
                title: "Fox and Snake",
                difficulty: "1100",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/510/A",
                tags: ["Implementation", "Simulation"],
                hint: "Simulate the snake pattern row by row. Odd rows go left-to-right, even rows go right-to-left. Connectors go vertically between row ends.",
                trigger:
                  "snake pattern + row direction alternation + simulation",
              },
              {
                id: "cf36",
                title: "BFS on a Graph",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/1209D",
                tags: ["BFS", "Graphs"],
                hint: "Standard BFS from source. Track distances. For each edge in answer, ensure it's a tree edge (d[v] = d[u] + 1). Count shortest path edges.",
                trigger: "BFS shortest path + count valid edges",
              },
              {
                id: "cf37",
                title: "String Reconstruction",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/472D",
                tags: ["Greedy", "Strings", "Sorting"],
                hint: "Sort strings by start position of their occurrence. Greedily extend covered range. If gap between covered range and next string, fill with string characters.",
                trigger: "interval covering + greedy + sort by position",
              },
            ],
          },
          {
            id: "cf-graph-adv",
            title: "Shortest Paths & Trees",
            description:
              "Dijkstra for weighted shortest paths. Tree problems need careful recursion.",
            problems: [
              {
                id: "cf38",
                title: "Dijkstra? (Classic)",
                difficulty: "1500",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/20/C",
                tags: ["Dijkstra", "Shortest Paths", "Graphs"],
                hint: "Classic Dijkstra. Min-heap (priority queue). For each node, relax neighbors. Reconstruct path by tracking previous nodes. Handle disconnected graph (output -1).",
                trigger:
                  "weighted shortest path + min heap + path reconstruction",
              },
              {
                id: "cf39",
                title: "Restoring the Path",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/632/E",
                tags: ["Dijkstra", "Shortest Paths", "Graphs"],
                hint: "Dijkstra from both source and destination. An edge (u,v) is on a shortest path if dist[s][u] + w(u,v) + dist[v][t] = dist[s][t].",
                trigger: "edge on shortest path + dijkstra from both ends",
              },
              {
                id: "cf40",
                title: "New Year Tree",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/379/F",
                tags: ["Trees", "DFS", "Bitmask"],
                hint: "Euler tour to flatten tree into array. Segment tree with lazy propagation for range updates. Colors fit in a 64-bit bitmask (at most 60 colors).",
                trigger: "euler tour + segment tree + bitmask for colors",
              },
            ],
          },
        ],
      },
      {
        id: "cf-dp",
        title: "Dynamic Programming",
        icon: "◫",
        description:
          "DP in competitive programming. Start with simple 1D DP and build up to more complex states.",
        subtopics: [
          {
            id: "cf-dp-basic",
            title: "Basic DP",
            description:
              "Classic DP problems that appear in Div. 2 C and early D problems.",
            problems: [
              {
                id: "cf41",
                title: "Knapsack",
                difficulty: "1500",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/19/B",
                tags: ["DP", "Greedy"],
                hint: "Classic 0/1 knapsack. dp[j] = can we make exactly weight j? Or greedy: sort by value/weight ratio. Depends on problem variant.",
                trigger: "pick items under weight limit + maximize value",
              },
              {
                id: "cf42",
                title: "Boredom",
                difficulty: "1500",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/455/C",
                tags: ["DP"],
                hint: "Collecting k means deleting all k-1 and k+1. This reduces to House Robber on value array where val[k] = k * count[k]. dp[i] = max(dp[i-1], dp[i-2] + val[i]).",
                trigger: "delete neighbors + house robber disguise + 1D DP",
              },
              {
                id: "cf43",
                title: "Leha and Function",
                difficulty: "1200",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/840/B",
                tags: ["Greedy", "Math", "Sorting"],
                hint: "f(n,k) increases as n increases (more divisors). Sort a descending and b descending. Pair largest a with largest b. Greedy matching.",
                trigger: "monotone function + sort both + pair greedily",
              },
              {
                id: "cf44",
                title: "Little Pony and Expected Value",
                difficulty: "1500",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/525/D",
                tags: ["DP", "Probability", "Math"],
                hint: "dp[i] = expected rolls to go from i hits to i+1 hits. With probability 1/6 you roll the right number. Expected value of geometric distribution = 6.",
                trigger: "expected value + geometric distribution + DP states",
              },
              {
                id: "cf45",
                title: "Regular Bracket Sequence",
                difficulty: "1400",
                platform: "codeforces",
                link: "https://codeforces.com/problemset/problem/380/D",
                tags: ["DP", "Strings", "Stacks"],
                hint: "DP where state includes current balance. dp[i][j] = ways to make valid sequence of length i with current balance j. Transition: add '(' (j→j+1) or ')' (j→j-1).",
                trigger: "count valid bracket sequences + DP on balance",
              },
            ],
          },
        ],
      },
    ],
  },
};
