window.DSA_DATA = {
  topics: [
    {
      id: 'arrays',
      name: 'Arrays',
      subtopics: [
        {
          id: 'array-basics',
          name: 'Array Basics',
          problems: [
            { id:'ab-001', name:'Two Sum', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/two-sum/', hint:'Use a hash map to store each number and its index. For each element, check if target-num exists in the map.', trigger:'When you see: find two numbers summing to target -> Hash map for O(1) complement lookup', tags:['hash-map','array'] },
            { id:'ab-002', name:'Best Time to Buy and Sell Stock', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', hint:'Track minimum price seen so far. For each price, profit = price - minSoFar, update max profit.', trigger:'When you see: single pass max profit one buy/sell -> Track running minimum', tags:['array','greedy'] },
            { id:'ab-003', name:'Contains Duplicate', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/contains-duplicate/', hint:'Add elements to a Set. If element already exists return true.', trigger:'When you see: check for duplicates -> Set for O(1) lookup', tags:['hash-set','array'] },
            { id:'ab-004', name:'Maximum Subarray', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/maximum-subarray/', hint:"Kadane's: keep running sum, reset to current element if running sum goes negative.", trigger:"When you see: maximum sum contiguous subarray -> Kadane's algorithm", tags:['dynamic-programming','array'] },
            { id:'ab-005', name:'Move Zeroes', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/move-zeroes/', hint:'Use write pointer (insertPos). Copy non-zero elements, fill rest with zeros.', trigger:'When you see: move elements to end in-place -> Two-pointer write technique', tags:['two-pointers','array'] },
            { id:'ab-006', name:'Plus One', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/plus-one/', hint:'Iterate from last digit. If digit < 9, increment and return. Else set 0, carry. Prepend 1 if all nines.', trigger:'When you see: increment digit array with carry -> Iterate from end, handle carry', tags:['array','math'] },
            { id:'ab-007', name:'Single Number', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/single-number/', hint:'XOR all numbers. Pairs cancel (a XOR a = 0). Result is the single number.', trigger:'When you see: find element appearing once among pairs -> XOR all elements', tags:['bit-manipulation','array'] },
            { id:'ab-008', name:'Intersection of Two Arrays II', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/intersection-of-two-arrays-ii/', hint:'Frequency map for smaller array. Iterate second array and decrement count when found.', trigger:'When you see: common elements with duplicates -> Frequency hash map', tags:['hash-map','array'] },
            { id:'ab-009', name:'Majority Element', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/majority-element/', hint:"Boyer-Moore Voting: maintain candidate and count. Increment if same, decrement otherwise. Reset at 0.", trigger:"When you see: element appearing > n/2 times -> Boyer-Moore Voting", tags:['array','voting'] },
            { id:'ab-010', name:'Missing Number', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/missing-number/', hint:'Expected sum n*(n+1)/2, subtract actual sum. Or XOR all indices and values.', trigger:'When you see: find missing in 0..n -> Math sum formula or XOR', tags:['math','bit-manipulation','array'] },
            { id:'ab-011', name:'Product of Array Except Self', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/product-of-array-except-self/', hint:'Build left-product array, then multiply right products in second pass. No division needed.', trigger:'When you see: product of all except self without division -> Left/right prefix products', tags:['array','prefix-product'] },
            { id:'ab-012', name:'Rotate Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/rotate-array/', hint:'Three-reverse trick: reverse entire, reverse first k, reverse rest. k = k % n.', trigger:'When you see: rotate array k steps in-place -> Three reversal technique', tags:['array','two-pointers'] },
            { id:'ab-013', name:'Max Consecutive Ones', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/max-consecutive-ones/', hint:'Track current count of consecutive 1s. Reset to 0 on 0.', trigger:'When you see: longest streak of same element -> Running counter reset on break', tags:['array'] },
            { id:'ab-014', name:'Running Sum of 1d Array', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/running-sum-of-1d-array/', hint:'Each element = nums[i] + nums[i-1]. Iterate from index 1.', trigger:'When you see: cumulative sum -> Prefix sum in-place', tags:['array','prefix-sum'] },
            { id:'ab-015', name:'Shuffle the Array', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/shuffle-the-array/', hint:'result[2i] = nums[i], result[2i+1] = nums[i+n].', trigger:'When you see: interleave first/second halves -> Index mapping formula', tags:['array'] }
          ]
        },
        {
          id: 'two-pointers',
          name: 'Two Pointers',
          problems: [
            { id:'tp-001', name:'Valid Palindrome', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/valid-palindrome/', hint:'Left and right pointers. Skip non-alphanumeric. Compare lowercase.', trigger:'When you see: palindrome check with extra chars -> Two pointers from both ends', tags:['two-pointers','string'] },
            { id:'tp-002', name:'3Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/3sum/', hint:'Sort. For each element i, two pointers (left, right) find pairs summing to -nums[i]. Skip duplicates.', trigger:'When you see: triplet summing to zero -> Sort + two pointers', tags:['two-pointers','sorting','array'] },
            { id:'tp-003', name:'Container With Most Water', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/container-with-most-water/', hint:'Two pointers from both ends. Move shorter pointer inward. Track max area.', trigger:'When you see: maximize container area -> Two pointers, move shorter side', tags:['two-pointers','greedy','array'] },
            { id:'tp-004', name:'Remove Duplicates from Sorted Array', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', hint:'Write pointer at 1. When nums[i] != nums[i-1], write and advance.', trigger:'When you see: remove duplicates in-place sorted -> Slow write pointer', tags:['two-pointers','array'] },
            { id:'tp-005', name:'Trapping Rain Water', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/trapping-rain-water/', hint:'Track maxLeft and maxRight. Water = min(maxLeft,maxRight) - height[i].', trigger:'When you see: trapped water -> Two pointers tracking running max from each side', tags:['two-pointers','array'] },
            { id:'tp-006', name:'Merge Sorted Array', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/merge-sorted-array/', hint:'Merge from back: i=m-1, j=n-1, k=m+n-1. Place larger at k.', trigger:'When you see: merge sorted in-place -> Fill from end', tags:['two-pointers','sorting','array'] },
            { id:'tp-007', name:'Two Sum II - Input Array Is Sorted', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/', hint:'Left and right pointers. If sum < target move left, else move right.', trigger:'When you see: two sum in sorted array -> Two pointers no extra space', tags:['two-pointers','binary-search'] },
            { id:'tp-008', name:'Boats to Save People', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/boats-to-save-people/', hint:'Sort. Try pair lightest with heaviest. If fit, advance both; else advance heavy alone.', trigger:'When you see: pair items under weight limit -> Sort + two pointers greedy pairing', tags:['two-pointers','greedy','sorting'] },
            { id:'tp-009', name:'Remove Element', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/remove-element/', hint:'Write pointer: copy elements not equal to val. Return write count.', trigger:'When you see: remove element in-place -> Write pointer', tags:['two-pointers','array'] },
            { id:'tp-010', name:'Sort Colors', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/sort-colors/', hint:'Dutch National Flag: low/mid/high pointers. Swap based on nums[mid].', trigger:'When you see: sort 3 distinct values one pass -> Dutch National Flag', tags:['two-pointers','sorting'] },
            { id:'tp-011', name:'Reverse String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/reverse-string/', hint:'Swap s[left] and s[right], move inward.', trigger:'When you see: reverse array in-place -> Two pointers swap from both ends', tags:['two-pointers','string'] },
            { id:'tp-012', name:'Squares of a Sorted Array', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/squares-of-a-sorted-array/', hint:'Two pointers at both ends. Place larger square at end of result. Move inward.', trigger:'When you see: square sorted array with negatives -> Two pointers fill from end', tags:['two-pointers','sorting','array'] }
          ]
        },
        {
          id: 'sliding-window',
          name: 'Sliding Window',
          problems: [
            { id:'sw-001', name:'Longest Substring Without Repeating Characters', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-substring-without-repeating-characters/', hint:'Expand right; if char in set, shrink from left until removed. Track max size.', trigger:'When you see: longest substring with unique elements -> Sliding window with hash set', tags:['sliding-window','hash-set','string'] },
            { id:'sw-002', name:'Maximum Average Subarray I', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/maximum-average-subarray-i/', hint:'Sum first k. Slide: add right, subtract left. Track max sum.', trigger:'When you see: max of fixed-size window -> Sliding window fixed size k', tags:['sliding-window','array'] },
            { id:'sw-003', name:'Minimum Window Substring', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/minimum-window-substring/', hint:'Expand right until all t chars covered. Shrink left to minimize. Two freq maps + formed counter.', trigger:'When you see: smallest window containing all chars of t -> Variable window with freq maps', tags:['sliding-window','hash-map','string'] },
            { id:'sw-004', name:'Longest Repeating Character Replacement', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-repeating-character-replacement/', hint:'Window valid if (size - maxFreq) <= k. Only expand right, shrink left when invalid.', trigger:'When you see: longest after at most k replacements -> Window valid when (size-maxFreq) <= k', tags:['sliding-window','string'] },
            { id:'sw-005', name:'Permutation in String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/permutation-in-string/', hint:'Fixed window of len(s1). Compare freq maps of window and s1. Slide and update.', trigger:'When you see: permutation of s1 in s2 -> Fixed-size window with freq map', tags:['sliding-window','hash-map','string'] },
            { id:'sw-006', name:'Max Consecutive Ones III', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/max-consecutive-ones-iii/', hint:'Count zeros in window. If zeros > k, move left. Track max window.', trigger:'When you see: flip at most k zeros for longest ones -> Sliding window counting zeros', tags:['sliding-window','array'] },
            { id:'sw-007', name:'Fruit Into Baskets', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/fruit-into-baskets/', hint:'At most 2 distinct types. Shrink left when distinct > 2. Track max.', trigger:'When you see: longest subarray at most k distinct -> Sliding window with freq map', tags:['sliding-window','hash-map','array'] },
            { id:'sw-008', name:'Minimum Size Subarray Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/minimum-size-subarray-sum/', hint:'Expand right. When sum >= target, record size and shrink from left.', trigger:'When you see: smallest subarray sum >= target -> Variable window shrink while condition met', tags:['sliding-window','array'] },
            { id:'sw-009', name:'Sliding Window Maximum', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/sliding-window-maximum/', hint:'Monotonic deque of indices. Remove out-of-window. Remove smaller from back. Front = max.', trigger:'When you see: max of each fixed window -> Monotonic deque', tags:['sliding-window','deque','monotonic-stack'] },
            { id:'sw-010', name:'Find All Anagrams in a String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-all-anagrams-in-a-string/', hint:'Fixed window len(p). Match freq maps. Add start index when matched.', trigger:'When you see: find all anagram starting indices -> Fixed window freq comparison', tags:['sliding-window','hash-map','string'] },
            { id:'sw-011', name:'Longest Subarray of 1s After Deleting One Element', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/', hint:'Allow at most 1 zero. When zeros > 1, shrink left. Result = window_size - 1.', trigger:'When you see: longest 1s after deleting one element -> Window with at most 1 zero, subtract 1', tags:['sliding-window','array'] },
            { id:'sw-012', name:'Number of Substrings Containing All Three Characters', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/', hint:'Find smallest valid left for each right. All substrings from valid-left to n are valid.', trigger:'When you see: count substrings with all k distinct -> Sliding window count from valid left', tags:['sliding-window','hash-map','string'] }
          ]
        },
        {
          id: 'prefix-sum',
          name: 'Prefix Sum',
          problems: [
            { id:'ps-001', name:'Range Sum Query - Immutable', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/range-sum-query-immutable/', hint:'Precompute prefix sums. Range sum [i,j] = prefix[j+1] - prefix[i].', trigger:'When you see: repeated range sum queries -> Precompute prefix sum array', tags:['prefix-sum','array'] },
            { id:'ps-002', name:'Subarray Sum Equals K', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/subarray-sum-equals-k/', hint:'Prefix sum + hash map. Count of prefix sums = currentSum - k gives valid subarrays ending here.', trigger:'When you see: count subarrays sum = k -> Prefix sum + hash map (currentSum - k lookup)', tags:['prefix-sum','hash-map','array'] },
            { id:'ps-003', name:'Continuous Subarray Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/continuous-subarray-sum/', hint:'Running sum mod k. Same remainder seen at j means subarray [j+1..i] divisible by k.', trigger:'When you see: subarray sum divisible by k -> Prefix sum mod k + first occurrence hash map', tags:['prefix-sum','hash-map','math'] },
            { id:'ps-004', name:'Find Pivot Index', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/find-pivot-index/', hint:'leftSum*2 + nums[i] == total means pivot found.', trigger:'When you see: index where left sum = right sum -> Prefix sum comparison with total', tags:['prefix-sum','array'] },
            { id:'ps-005', name:'Minimum Operations to Reduce X to Zero', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/', hint:'Equivalent to longest subarray with sum = totalSum - x. Use sliding window.', trigger:'When you see: minimize removed from both ends -> Flip to maximize middle subarray', tags:['prefix-sum','sliding-window','array'] },
            { id:'ps-006', name:'Contiguous Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/contiguous-array/', hint:'Replace 0 with -1. Find longest subarray with sum = 0 using prefix sum + hash map.', trigger:'When you see: equal 0s and 1s -> Replace 0->-1, find longest zero-sum subarray', tags:['prefix-sum','hash-map','array'] },
            { id:'ps-007', name:'Find the Highest Altitude', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/find-the-highest-altitude/', hint:'Running prefix sum of gain array. Max prefix sum is highest altitude.', trigger:'When you see: running cumulative sum then find max -> Prefix sum then max', tags:['prefix-sum','array'] },
            { id:'ps-008', name:'Left and Right Sum Differences', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/left-and-right-sum-differences/', hint:'Prefix + suffix sums. answer[i] = |leftSum[i] - rightSum[i]|.', trigger:'When you see: absolute difference of sums on each side -> Prefix + suffix arrays', tags:['prefix-sum','array'] },
            { id:'ps-009', name:'Maximum Sum of an Hourglass', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/maximum-sum-of-an-hourglass/', hint:'Iterate all valid hourglass centers. Sum 7 cells for each, track max.', trigger:'When you see: fixed-shape subgrid maximum -> Iterate all valid positions, compute shape sum', tags:['array','matrix'] },
            { id:'ps-010', name:'Sum of Absolute Differences in a Sorted Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/sum-of-absolute-differences-in-a-sorted-array/', hint:'Left: nums[i]*i - prefixSum[i]. Right: suffixSum[i] - nums[i]*(n-i). Use prefix/suffix sums.', trigger:'When you see: sum of abs differences from each element -> Prefix/suffix sums + index math', tags:['prefix-sum','array','math'] }
          ]
        }
      ]
    },
    {
      id: 'strings',
      name: 'Strings',
      subtopics: [
        {
          id: 'string-basics',
          name: 'String Basics',
          problems: [
            { id:'sb-001', name:'Valid Anagram', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/valid-anagram/', hint:'Count char frequencies of both strings using array or hash map. Compare them.', trigger:'When you see: check if two strings are anagrams -> Character frequency count', tags:['hash-map','string'] },
            { id:'sb-002', name:'Reverse Words in a String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/reverse-words-in-a-string/', hint:'Split by whitespace, filter empty, reverse array, join with single space.', trigger:'When you see: reverse word order -> Split, reverse, join', tags:['string','two-pointers'] },
            { id:'sb-003', name:'First Unique Character in a String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/first-unique-character-in-a-string/', hint:'Count all char freqs. Iterate again to find first with freq == 1.', trigger:'When you see: first non-repeating character -> Two-pass: count freq, find first with count 1', tags:['hash-map','string'] },
            { id:'sb-004', name:'Valid Palindrome II', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/valid-palindrome-ii/', hint:'Two pointers. On mismatch, try skipping left or right, check if remaining is palindrome.', trigger:'When you see: palindrome after deleting at most one char -> Try skipping each mismatch', tags:['two-pointers','string'] },
            { id:'sb-005', name:'Longest Common Prefix', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/longest-common-prefix/', hint:'Start with first string as prefix. Trim until each string starts with it.', trigger:'When you see: common prefix of multiple strings -> Iterative trimming', tags:['string'] },
            { id:'sb-006', name:'Ransom Note', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/ransom-note/', hint:'Count magazine chars. For each ransomNote char, decrement. If negative, return false.', trigger:'When you see: can we form string from another -> Frequency count of source', tags:['hash-map','string'] },
            { id:'sb-007', name:'Is Subsequence', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/is-subsequence/', hint:'Two pointers. Advance s-pointer when chars match. If s-pointer reaches end, return true.', trigger:'When you see: check if s is subsequence of t -> Two pointers advancing through both', tags:['two-pointers','string'] },
            { id:'sb-008', name:'Roman to Integer', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/roman-to-integer/', hint:'Map symbol to value. If current < next, subtract; else add.', trigger:'When you see: Roman numeral -> Check if current < next, then subtract', tags:['hash-map','math','string'] },
            { id:'sb-009', name:'Count and Say', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/count-and-say/', hint:'Iteratively build from previous: group consecutive same digits, write count+digit.', trigger:'When you see: run-length encoding iteratively -> Group consecutive same chars', tags:['string'] },
            { id:'sb-010', name:'String Compression', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/string-compression/', hint:'Two pointers (read/write). Group consecutive same chars, write char then count if > 1.', trigger:'When you see: compress string in-place -> Two pointers, count consecutive runs', tags:['two-pointers','string'] },
            { id:'sb-011', name:'Reverse Vowels of a String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/reverse-vowels-of-a-string/', hint:'Two pointers. Move until vowel, swap, repeat.', trigger:'When you see: swap specific char type -> Two pointers targeting only those chars', tags:['two-pointers','string'] },
            { id:'sb-012', name:'Find the Index of the First Occurrence in a String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/', hint:'KMP or sliding window: check each window of len(needle).', trigger:'When you see: first occurrence of substring -> Sliding window compare or KMP', tags:['string','kmp'] }
          ]
        },
        {
          id: 'string-manipulation',
          name: 'String Manipulation',
          problems: [
            { id:'sm-001', name:'Longest Palindromic Substring', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-palindromic-substring/', hint:'Expand around center for odd and even centers. Track longest expansion.', trigger:'When you see: longest palindrome substring -> Expand around every center', tags:['string','dynamic-programming'] },
            { id:'sm-002', name:'Group Anagrams', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/group-anagrams/', hint:'Sort each word as canonical key. Group same-key words in hash map.', trigger:'When you see: group anagram strings -> Sorted string as hash map key', tags:['hash-map','string','sorting'] },
            { id:'sm-003', name:'Encode and Decode Strings', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/encode-and-decode-strings/', hint:'Encode as "length#string". Decode by reading length then "#" then exactly that many chars.', trigger:'When you see: serialize list of strings -> Length-prefixed encoding', tags:['string','design'] },
            { id:'sm-004', name:'Zigzag Conversion', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/zigzag-conversion/', hint:'numRows builders. Simulate: increment/decrement row, change direction at top/bottom.', trigger:'When you see: zigzag string pattern -> Simulate row index going up/down', tags:['string'] },
            { id:'sm-005', name:'Multiply Strings', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/multiply-strings/', hint:'digits[i]*digits[j] -> result[i+j] and result[i+j+1]. Fill result array, convert to string.', trigger:'When you see: multiply large number strings -> Index mapping result[i+j], result[i+j+1]', tags:['math','string'] },
            { id:'sm-006', name:'Add Strings', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/add-strings/', hint:'Two pointers from end. Add digits + carry. Handle remaining carry.', trigger:'When you see: add large number strings -> Simulate addition from right with carry', tags:['math','string'] },
            { id:'sm-007', name:'Integer to Roman', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/integer-to-roman/', hint:'Descending value-symbol table. Greedily append largest fitting symbol.', trigger:'When you see: integer to Roman -> Greedy with descending value-symbol table', tags:['math','string','greedy'] },
            { id:'sm-008', name:'Reverse String II', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/reverse-string-ii/', hint:'Iterate by 2k. Reverse first k of each chunk.', trigger:'When you see: reverse every 2k first k chars -> Iterate by 2k, reverse slice', tags:['string','two-pointers'] },
            { id:'sm-009', name:'Repeated Substring Pattern', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/repeated-substring-pattern/', hint:'If s is repeated pattern, (s+s)[1:-1] still contains s.', trigger:"When you see: check repeated pattern -> s in (s+s)[1:-1] trick", tags:['string','kmp'] },
            { id:'sm-010', name:'Find and Replace Pattern', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-and-replace-pattern/', hint:'Normalize both word and pattern to index-based canonical form. Compare.', trigger:'When you see: structural pattern matching of strings -> Normalize to index canonical form', tags:['hash-map','string'] },
            { id:'sm-011', name:'Shuffle String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/shuffle-string/', hint:'result[indices[i]] = s[i] for each i.', trigger:'When you see: rearrange string by index mapping -> Direct index placement', tags:['string','array'] },
            { id:'sm-012', name:'Reorder Data in Log Files', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/reorder-data-in-log-files/', hint:'Separate letter and digit logs. Sort letter logs by content then id. Append digit logs in order.', trigger:'When you see: custom sort with multiple criteria -> Separate by type, custom comparator', tags:['string','sorting'] }
          ]
        }
      ]
    },
    {
      id: 'linked-list',
      name: 'Linked List',
      subtopics: [
        {
          id: 'singly-linked-list',
          name: 'Singly Linked List',
          problems: [
            { id:'sll-001', name:'Reverse Linked List', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/reverse-linked-list/', hint:'Three pointers: prev, curr, next. Redirect curr.next to prev, advance all.', trigger:'When you see: reverse linked list -> Three pointer redirect (prev, curr, next)', tags:['linked-list','recursion'] },
            { id:'sll-002', name:'Middle of the Linked List', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/middle-of-the-linked-list/', hint:'Fast moves 2 steps, slow 1. When fast reaches end, slow is at middle.', trigger:'When you see: find middle of list -> Fast (2x) and slow (1x) pointers', tags:['linked-list','two-pointers'] },
            { id:'sll-003', name:'Merge Two Sorted Lists', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/merge-two-sorted-lists/', hint:'Dummy head. Compare l1 and l2, attach smaller. Advance that pointer. Attach remaining.', trigger:'When you see: merge two sorted lists -> Dummy node + compare-attach smaller', tags:['linked-list','recursion'] },
            { id:'sll-004', name:'Remove Nth Node From End of List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', hint:'Advance fast n+1 steps. Move both until fast null. Slow is before target.', trigger:'When you see: remove/find nth from end -> Two pointers with n-step gap', tags:['linked-list','two-pointers'] },
            { id:'sll-005', name:'Linked List Cycle', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/linked-list-cycle/', hint:"Floyd's: fast and slow. If they meet, cycle exists.", trigger:"When you see: detect cycle -> Floyd's (fast/slow meet = cycle)", tags:['linked-list','two-pointers'] },
            { id:'sll-006', name:'Palindrome Linked List', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/palindrome-linked-list/', hint:'Find middle, reverse second half, compare first and second halves.', trigger:'When you see: palindrome check on list -> Find middle + reverse second half + compare', tags:['linked-list','two-pointers'] },
            { id:'sll-007', name:'Delete Node in a Linked List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/delete-node-in-a-linked-list/', hint:'Copy next node value to current, bypass next node.', trigger:'When you see: delete node without head pointer -> Copy next value, skip next', tags:['linked-list'] },
            { id:'sll-008', name:'Add Two Numbers', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/add-two-numbers/', hint:'Traverse both lists, add digits + carry. Create new node per sum.', trigger:'When you see: add reversed-digit lists -> Traverse + carry propagation', tags:['linked-list','math'] },
            { id:'sll-009', name:'Remove Duplicates from Sorted List', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/remove-duplicates-from-sorted-list/', hint:'If curr.val == curr.next.val, skip next: curr.next = curr.next.next.', trigger:'When you see: remove duplicates from sorted list -> Skip when curr equals next', tags:['linked-list'] },
            { id:'sll-010', name:'Intersection of Two Linked Lists', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/intersection-of-two-linked-lists/', hint:'When pointer reaches end, redirect to other list head. They meet at intersection.', trigger:'When you see: intersection of two lists -> Redirect to opposite list heads', tags:['linked-list','two-pointers'] },
            { id:'sll-011', name:'Merge k Sorted Lists', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/merge-k-sorted-lists/', hint:'Min-heap of (value, listIndex, node). Extract min, push next from that list.', trigger:'When you see: merge k sorted lists -> Min-heap with one element per list', tags:['linked-list','heap'] },
            { id:'sll-012', name:'Reverse Nodes in k-Group', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/reverse-nodes-in-k-group/', hint:'Check k nodes exist. Reverse k, recurse for rest. Connect reversed group to result.', trigger:'When you see: reverse in groups of k -> Reverse k nodes + recurse on remainder', tags:['linked-list','recursion'] }
          ]
        },
        {
          id: 'fast-slow-pointers',
          name: 'Fast & Slow Pointers',
          problems: [
            { id:'fsp-001', name:'Linked List Cycle II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/linked-list-cycle-ii/', hint:"Floyd's detect cycle. Reset one pointer to head. Both advance by 1; meet at cycle start.", trigger:"When you see: find cycle start -> Floyd's + reset one to head", tags:['linked-list','two-pointers'] },
            { id:'fsp-002', name:'Find the Duplicate Number', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-the-duplicate-number/', hint:"Treat array as linked list (index->value). Floyd's cycle. Reset slow=0, advance both by 1.", trigger:"When you see: duplicate in array[1..n] without extra space -> Model as list, Floyd's cycle", tags:['array','two-pointers'] },
            { id:'fsp-003', name:'Happy Number', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/happy-number/', hint:'Apply digit-square-sum. Fast/slow or hash set to detect cycle. Cycle on 1 = happy.', trigger:'When you see: detect loop in sequence -> Fast/slow or hash set', tags:['hash-set','math','two-pointers'] },
            { id:'fsp-004', name:'Circular Array Loop', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/circular-array-loop/', hint:"Floyd's on each start index. Validate: all same direction, length > 1.", trigger:"When you see: cycle in circular array -> Floyd's per start, validate direction/length", tags:['array','two-pointers'] },
            { id:'fsp-005', name:'Sort List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/sort-list/', hint:'Merge sort: find middle (fast/slow), split, sort both halves, merge.', trigger:'When you see: sort linked list O(n log n) -> Merge sort with fast/slow split', tags:['linked-list','sorting'] },
            { id:'fsp-006', name:'Reorder List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/reorder-list/', hint:'Find middle, reverse second half, interleave both halves.', trigger:'When you see: reorder L0->Ln->L1->Ln-1 -> Find middle + reverse second + merge', tags:['linked-list','two-pointers'] },
            { id:'fsp-007', name:'Remove Linked List Elements', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/remove-linked-list-elements/', hint:'Dummy node. If next.val == val, skip. Else advance.', trigger:'When you see: remove nodes by value -> Dummy node + skip matching', tags:['linked-list'] },
            { id:'fsp-008', name:'Odd Even Linked List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/odd-even-linked-list/', hint:'Two chains: odd and even. Connect end of odd to head of even.', trigger:'When you see: rearrange odd/even indexed nodes -> Two chains reconnected', tags:['linked-list'] },
            { id:'fsp-009', name:'Rotate List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/rotate-list/', hint:'Find length, k = k%len. New tail at (len-k-1). Cut and reconnect.', trigger:'When you see: rotate list by k -> Find length, new tail at len-k', tags:['linked-list','two-pointers'] },
            { id:'fsp-010', name:'Partition List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/partition-list/', hint:'Two dummies: one for < x, one for >= x. Append each node appropriately, connect.', trigger:'When you see: partition list around value -> Two separate chains reconnected', tags:['linked-list','two-pointers'] }
          ]
        }
      ]
    },
    {
      id: 'stack-queue',
      name: 'Stack & Queue',
      subtopics: [
        {
          id: 'stack',
          name: 'Stack',
          problems: [
            { id:'st-001', name:'Valid Parentheses', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/valid-parentheses/', hint:'Push opening brackets. On closing, check if top matches opener.', trigger:'When you see: balanced brackets -> Stack (push open, match on close)', tags:['stack','string'] },
            { id:'st-002', name:'Min Stack', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/min-stack/', hint:'Two stacks: main + min-tracker. Push min(current, minStack top) each push.', trigger:'When you see: stack with O(1) min -> Parallel min-stack', tags:['stack','design'] },
            { id:'st-003', name:'Evaluate Reverse Polish Notation', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/evaluate-reverse-polish-notation/', hint:'Push numbers. On operator, pop two, apply, push result.', trigger:'When you see: evaluate RPN -> Stack for operands, apply on operator', tags:['stack','math'] },
            { id:'st-004', name:'Daily Temperatures', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/daily-temperatures/', hint:'Monotonic decreasing stack of indices. Pop when current > top. Diff = answer.', trigger:'When you see: next greater element to right -> Monotonic decreasing stack', tags:['stack','array','monotonic-stack'] },
            { id:'st-005', name:'Next Greater Element I', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/next-greater-element-i/', hint:'Process nums2 with monotonic stack, build next-greater map. Lookup nums1.', trigger:'When you see: next greater element mapping -> Monotonic stack on full array + hash map', tags:['stack','hash-map','monotonic-stack'] },
            { id:'st-006', name:'Largest Rectangle in Histogram', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/largest-rectangle-in-histogram/', hint:'Monotonic increasing stack. Pop when shorter. Width = curr_idx - top - 1. Add 0 sentinel.', trigger:'When you see: largest rectangle in histogram -> Monotonic increasing stack, area on pop', tags:['stack','array','monotonic-stack'] },
            { id:'st-007', name:'Trapping Rain Water', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/trapping-rain-water/', hint:'Decreasing stack. When curr > top, compute water = (min(left,right)-bottom)*width.', trigger:'When you see: trapped water via stack -> Monotonic stack, compute bounded water on pop', tags:['stack','two-pointers','array'] },
            { id:'st-008', name:'Remove K Digits', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/remove-k-digits/', hint:'Monotonic increasing stack. Pop larger digit when current smaller and k > 0.', trigger:'When you see: remove k digits for smallest number -> Monotonic stack, pop on smaller digit', tags:['stack','greedy','string'] },
            { id:'st-009', name:'Score of Parentheses', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/score-of-parentheses/', hint:'Stack: push 0 for "(". On ")" combine with previous score.', trigger:'When you see: score of nested parentheses -> Stack tracking accumulated score per level', tags:['stack','string'] },
            { id:'st-010', name:'Decode String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/decode-string/', hint:'Stack: push (str, count) on "[". On "]" pop and repeat current string count times.', trigger:'When you see: decode k[...] pattern -> Stack storing (str, count) per nesting level', tags:['stack','string','recursion'] },
            { id:'st-011', name:'Simplify Path', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/simplify-path/', hint:'Split by "/". Push dir names, pop on "..", skip "." and empty.', trigger:'When you see: simplify file path with . and .. -> Stack push dirs, pop on ..', tags:['stack','string'] },
            { id:'st-012', name:'Car Fleet', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/car-fleet/', hint:'Sort by position descending. Compute arrival time. If <= top, merges. Else push.', trigger:'When you see: cars merging into fleets -> Sort by position, time-based monotonic stack', tags:['stack','sorting','array'] }
          ]
        },
        {
          id: 'queue',
          name: 'Queue',
          problems: [
            { id:'qu-001', name:'Implement Queue using Stacks', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/implement-queue-using-stacks/', hint:'Two stacks inbox/outbox. Push to inbox. Pop from outbox; if empty transfer all from inbox.', trigger:'When you see: implement queue with stacks -> Two stacks, lazy transfer', tags:['stack','queue','design'] },
            { id:'qu-002', name:'Sliding Window Maximum', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/sliding-window-maximum/', hint:'Monotonic deque of indices. Remove out-of-window. Remove smaller from back. Front = max.', trigger:'When you see: maximum in each sliding window -> Monotonic deque', tags:['queue','deque','sliding-window'] },
            { id:'qu-003', name:'Design Circular Queue', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/design-circular-queue/', hint:'Array with head, tail, count. Use modulo for wrap-around.', trigger:'When you see: circular queue -> Array + head/tail pointers with (ptr+1)%capacity', tags:['queue','design','array'] },
            { id:'qu-004', name:'Implement Stack using Queues', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/implement-stack-using-queues/', hint:'After enqueue, rotate n-1 times so newest is at front.', trigger:'When you see: stack from queues -> Rotate new element to front', tags:['stack','queue','design'] },
            { id:'qu-005', name:'First Unique Character in a String', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/first-unique-character-in-a-string/', hint:'Count freqs. Find first char with freq == 1. Return index.', trigger:'When you see: first non-repeating in stream -> Two-pass frequency count', tags:['hash-map','string','queue'] },
            { id:'qu-006', name:'Number of Recent Calls', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/number-of-recent-calls/', hint:'Queue calls. Remove from front if older than t-3000. Return size.', trigger:'When you see: count events in sliding time window -> Queue, dequeue expired', tags:['queue','design'] },
            { id:'qu-007', name:'Moving Average from Data Stream', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/moving-average-from-data-stream/', hint:'Fixed-size queue + running sum. Remove oldest when exceeds size.', trigger:'When you see: moving average over last k -> Fixed-size queue + running sum', tags:['queue','design','sliding-window'] },
            { id:'qu-008', name:'Design Hit Counter', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/design-hit-counter/', hint:'Queue of timestamps. Remove older than timestamp-300. Return size.', trigger:'When you see: count hits in last 5 minutes -> Queue, dequeue stale entries', tags:['queue','design'] },
            { id:'qu-009', name:'Task Scheduler', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/task-scheduler/', hint:'max(n_tasks, (maxFreq-1)*(n+1) + count_of_maxFreq).', trigger:'When you see: schedule tasks with cooling time -> Frequency-based formula with idle slots', tags:['queue','heap','greedy','hash-map'] },
            { id:'qu-010', name:'Rotting Oranges', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/rotting-oranges/', hint:'Multi-source BFS from all rotten oranges. Each level = 1 minute.', trigger:'When you see: minimum time to spread/infect -> Multi-source BFS', tags:['bfs','queue','matrix'] },
            { id:'qu-011', name:'Perfect Squares', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/perfect-squares/', hint:'BFS from n. Subtract all perfect squares <= n. First level reaching 0 = answer. Or DP.', trigger:'When you see: minimum steps to reach 0 -> BFS level count or DP', tags:['bfs','queue','dynamic-programming'] },
            { id:'qu-012', name:'Walls and Gates', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/walls-and-gates/', hint:'Multi-source BFS from all gates (0s). Spread distance outward to INF cells.', trigger:'When you see: fill cells with distance to nearest gate -> Multi-source BFS', tags:['bfs','queue','matrix'] }
          ]
        }
      ]
    },
    {
      id: 'trees',
      name: 'Trees',
      subtopics: [
        {
          id: 'binary-tree-basics',
          name: 'Binary Tree Basics',
          problems: [
            { id:'bt-001', name:'Maximum Depth of Binary Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/maximum-depth-of-binary-tree/', hint:'Recursive: 1 + max(depth(left), depth(right)). Null returns 0.', trigger:'When you see: tree depth/height -> Recursive max of left/right + 1', tags:['tree','dfs','recursion'] },
            { id:'bt-002', name:'Binary Tree Inorder Traversal', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/binary-tree-inorder-traversal/', hint:'Left -> Root -> Right. Iterative: stack, go left until null, process, go right.', trigger:'When you see: inorder traversal -> Left -> Root -> Right', tags:['tree','dfs','stack'] },
            { id:'bt-003', name:'Symmetric Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/symmetric-tree/', hint:'isMirror(left, right): values equal, left.left mirrors right.right, left.right mirrors right.left.', trigger:'When you see: symmetric tree -> Compare subtrees as mirrors', tags:['tree','dfs','bfs'] },
            { id:'bt-004', name:'Path Sum', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/path-sum/', hint:'DFS: subtract current value. At leaf if remaining == 0, return true.', trigger:'When you see: root-to-leaf path sum -> DFS subtract from target, check at leaf', tags:['tree','dfs','recursion'] },
            { id:'bt-005', name:'Diameter of Binary Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/diameter-of-binary-tree/', hint:'For each node: diameter = left_height + right_height. Track global max. Return height.', trigger:'When you see: diameter = longest path -> left_height + right_height per node', tags:['tree','dfs','recursion'] },
            { id:'bt-006', name:'Invert Binary Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/invert-binary-tree/', hint:'Swap children. Recurse on both subtrees.', trigger:'When you see: mirror/invert tree -> Swap children recursively', tags:['tree','dfs','bfs'] },
            { id:'bt-007', name:'Same Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/same-tree/', hint:'Both null -> true. One null or values differ -> false. Else check both subtrees.', trigger:'When you see: two identical trees -> Recursive compare null/value/subtrees', tags:['tree','dfs','recursion'] },
            { id:'bt-008', name:'Subtree of Another Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/subtree-of-another-tree/', hint:'Check isSameTree(node, subRoot) for every node in main tree.', trigger:'When you see: subtree check -> isSameTree at every node', tags:['tree','dfs'] },
            { id:'bt-009', name:'Lowest Common Ancestor of a Binary Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', hint:'If root is p or q return root. Recurse left/right. If both non-null, root is LCA.', trigger:'When you see: LCA binary tree -> Return root when both sides non-null', tags:['tree','dfs','recursion'] },
            { id:'bt-010', name:'Binary Tree Level Order Traversal', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/binary-tree-level-order-traversal/', hint:'BFS with queue. Process levelSize nodes per iteration.', trigger:'When you see: level-by-level traversal -> BFS, snapshot levelSize each round', tags:['tree','bfs','queue'] },
            { id:'bt-011', name:'Binary Tree Maximum Path Sum', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/binary-tree-maximum-path-sum/', hint:'gain = max(0,leftG) + max(0,rightG) + val. Update global max. Return val + max(leftG,rightG).', trigger:'When you see: max path through any node -> DFS returning single-side gain', tags:['tree','dfs','dynamic-programming'] },
            { id:'bt-012', name:'Balanced Binary Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/balanced-binary-tree/', hint:'Return -1 if unbalanced. If |leftH - rightH| > 1 propagate -1, else return height.', trigger:'When you see: check balanced -> DFS returning -1 for unbalanced, height otherwise', tags:['tree','dfs','recursion'] }
          ]
        },
        {
          id: 'bst',
          name: 'BST',
          problems: [
            { id:'bst-001', name:'Validate Binary Search Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/validate-binary-search-tree/', hint:'Pass min/max bounds. Left: max=node.val. Right: min=node.val.', trigger:'When you see: validate BST -> Pass (min, max) bounds recursively', tags:['tree','dfs','recursion'] },
            { id:'bst-002', name:'Search in a Binary Search Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/search-in-a-binary-search-tree/', hint:'Compare val with root.val. Smaller go left, larger go right.', trigger:'When you see: search BST -> Compare and go left/right', tags:['tree','bst','recursion'] },
            { id:'bst-003', name:'Insert into a Binary Search Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/insert-into-a-binary-search-tree/', hint:'Recurse left/right. Insert at null child.', trigger:'When you see: insert into BST -> Recurse, insert at null child', tags:['tree','bst','recursion'] },
            { id:'bst-004', name:'Delete Node in a BST', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/delete-node-in-a-bst/', hint:'Leaf: delete. One child: return that child. Two children: replace with inorder successor.', trigger:'When you see: delete BST node -> 3 cases: leaf, one child, two children (inorder successor)', tags:['tree','bst','recursion'] },
            { id:'bst-005', name:'Kth Smallest Element in a BST', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', hint:'Inorder gives sorted. Return kth element. Early stop with iterative inorder.', trigger:'When you see: kth smallest in BST -> Inorder traversal, count to k', tags:['tree','bst','dfs'] },
            { id:'bst-006', name:'Range Sum of BST', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/range-sum-of-bst/', hint:'Add node.val if in range. Only go left if low < root.val, right if high > root.val.', trigger:'When you see: sum in BST range -> Prune: skip left if low >= root, right if high <= root', tags:['tree','bst','dfs'] },
            { id:'bst-007', name:'Lowest Common Ancestor of a Binary Search Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', hint:'If both < root go left, both > root go right, else root is LCA.', trigger:'When you see: LCA in BST -> Follow direction until split point', tags:['tree','bst','dfs'] },
            { id:'bst-008', name:'Closest Binary Search Tree Value', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/closest-binary-search-tree-value/', hint:'At each node update closest. Go left if target < node.val, else right.', trigger:'When you see: closest value in BST -> BST search, update closest at each node', tags:['tree','bst','binary-search'] },
            { id:'bst-009', name:'Two Sum IV - Input is a BST', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/', hint:'Inorder to sorted array + two-pointer. Or DFS + hash set.', trigger:'When you see: two sum in BST -> Inorder + two pointers, or DFS + hash set', tags:['tree','bst','hash-set'] },
            { id:'bst-010', name:'Convert Sorted Array to Binary Search Tree', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/', hint:'Middle element as root. Recurse left and right halves.', trigger:'When you see: balanced BST from sorted array -> Middle as root, recurse halves', tags:['tree','bst','divide-and-conquer'] }
          ]
        },
        {
          id: 'tree-dfs-bfs',
          name: 'Tree DFS/BFS',
          problems: [
            { id:'tdb-001', name:'Path Sum II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/path-sum-ii/', hint:'DFS with current path. At leaf with target==0, save copy. Backtrack.', trigger:'When you see: all root-to-leaf paths with target -> DFS backtracking, copy at leaf', tags:['tree','dfs','backtracking'] },
            { id:'tdb-002', name:'Binary Tree Right Side View', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/binary-tree-right-side-view/', hint:'BFS level order. Last node in each level is visible.', trigger:'When you see: right side view -> BFS, last node of each level', tags:['tree','bfs','dfs'] },
            { id:'tdb-003', name:'Sum Root to Leaf Numbers', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/sum-root-to-leaf-numbers/', hint:'DFS passing num = prev*10 + node.val. At leaf, add to total.', trigger:'When you see: sum of root-to-leaf numbers -> DFS building number prev*10+digit', tags:['tree','dfs','recursion'] },
            { id:'tdb-004', name:'Count Good Nodes in Binary Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/count-good-nodes-in-binary-tree/', hint:'DFS passing max seen on path. Good if val >= maxSoFar.', trigger:'When you see: count nodes >= all ancestors -> DFS tracking running max', tags:['tree','dfs','recursion'] },
            { id:'tdb-005', name:'Serialize and Deserialize Binary Tree', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', hint:'Preorder DFS serialize with null markers. Deserialize consuming token queue.', trigger:'When you see: serialize tree -> Preorder with null markers; deserialize with token queue', tags:['tree','dfs','design'] },
            { id:'tdb-006', name:'Construct Binary Tree from Preorder and Inorder Traversal', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', hint:'preorder[0] is root. Find in inorder (hash map). Left = inorder left of root.', trigger:'When you see: build tree from preorder+inorder -> Root=preorder[0], split inorder', tags:['tree','dfs','hash-map'] },
            { id:'tdb-007', name:'Binary Tree Zigzag Level Order Traversal', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', hint:'BFS level order. Alternate direction each level.', trigger:'When you see: zigzag level order -> BFS, alternate direction each level', tags:['tree','bfs','queue'] },
            { id:'tdb-008', name:'Populating Next Right Pointers in Each Node', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', hint:'Use already-set next pointers for O(1) space. Set children next via current level.', trigger:'When you see: set next pointers O(1) space -> Use current level next to traverse', tags:['tree','bfs'] },
            { id:'tdb-009', name:'Flatten Binary Tree to Linked List', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', hint:'Find rightmost of left subtree, attach right there, move left to right, null left.', trigger:'When you see: flatten tree to list in-place -> Find leftmost right, rewire', tags:['tree','dfs','linked-list'] },
            { id:'tdb-010', name:'Count Complete Tree Nodes', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/count-complete-tree-nodes/', hint:'Compare left and right heights. Equal: left is perfect 2^h-1, recurse right. Else recurse left.', trigger:'When you see: count complete tree nodes -> Compare heights O(log^2 n)', tags:['tree','binary-search','dfs'] },
            { id:'tdb-011', name:'Vertical Order Traversal of a Binary Tree', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/', hint:'DFS assigns (col, row, val). Sort by col, row, val. Group by col.', trigger:'When you see: vertical order tree -> Assign (col, row) to each node, sort', tags:['tree','dfs','bfs','sorting'] },
            { id:'tdb-012', name:'Find Largest Value in Each Tree Row', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-largest-value-in-each-tree-row/', hint:'BFS level order. Track max value in each level.', trigger:'When you see: max per level -> BFS, track max in each level', tags:['tree','bfs','dfs'] }
          ]
        }
      ]
    },
    {
      id: 'graphs',
      name: 'Graphs',
      subtopics: [
        {
          id: 'graph-basics',
          name: 'Graph Basics',
          problems: [
            { id:'gb-001', name:'Number of Islands', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/number-of-islands/', hint:"DFS/BFS from each '1'. Mark visited as '0'. Count starts.", trigger:'When you see: count connected components in grid -> DFS/BFS mark visited, count starts', tags:['dfs','bfs','matrix','union-find'] },
            { id:'gb-002', name:'Clone Graph', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/clone-graph/', hint:'DFS + hash map (orig->clone). If in map return clone. Else create, add, recurse neighbors.', trigger:'When you see: deep clone graph -> DFS + hash map (original -> clone)', tags:['dfs','bfs','hash-map','graph'] },
            { id:'gb-003', name:'Course Schedule', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/course-schedule/', hint:'DFS cycle detection. States: 0=unvisited, 1=visiting, 2=done. Cycle if hit visiting node.', trigger:'When you see: detect cycle in directed graph -> DFS 3-state cycle detection', tags:['dfs','topological-sort','graph'] },
            { id:'gb-004', name:'Pacific Atlantic Water Flow', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/pacific-atlantic-water-flow/', hint:'BFS from Pacific and Atlantic borders separately. Intersect reachable sets.', trigger:'When you see: reachable to two targets -> Reverse BFS from both, intersect results', tags:['dfs','bfs','matrix','graph'] },
            { id:'gb-005', name:'Number of Connected Components in an Undirected Graph', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/', hint:'DFS/BFS or Union-Find. Count DFS starts or distinct UF roots.', trigger:'When you see: count connected components -> DFS/BFS or Union-Find', tags:['dfs','bfs','union-find','graph'] },
            { id:'gb-006', name:'Graph Valid Tree', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/graph-valid-tree/', hint:'Valid tree = n-1 edges + connected. Union-Find: cycle if edge connects already-connected.', trigger:'When you see: valid tree check -> n-1 edges + no cycle (Union-Find or DFS)', tags:['dfs','bfs','union-find','graph'] },
            { id:'gb-007', name:'Find if Path Exists in Graph', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/find-if-path-exists-in-graph/', hint:'BFS/DFS from source. Return true if destination reachable.', trigger:'When you see: path existence between nodes -> BFS/DFS or Union-Find', tags:['dfs','bfs','union-find','graph'] },
            { id:'gb-008', name:'Flood Fill', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/flood-fill/', hint:'DFS from start. Change color of connected same-color cells. Skip if already new color.', trigger:'When you see: flood-fill connected region -> DFS change color, skip if already changed', tags:['dfs','bfs','matrix'] },
            { id:'gb-009', name:'Max Area of Island', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/max-area-of-island/', hint:"DFS from each '1'. Return area of component. Track maximum.", trigger:'When you see: largest connected component in grid -> DFS returning component size', tags:['dfs','bfs','matrix'] },
            { id:'gb-010', name:'Keys and Rooms', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/keys-and-rooms/', hint:'DFS/BFS from room 0 using keys as edges. All rooms visited = true.', trigger:'When you see: reachability with key-door mechanics -> DFS/BFS with keys as edges', tags:['dfs','bfs','graph'] },
            { id:'gb-011', name:'Surrounded Regions', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/surrounded-regions/', hint:"DFS from border O's: mark safe. Remaining O's surrounded. Flip to X, restore safe.", trigger:'When you see: capture enclosed regions -> DFS from borders for safe cells, flip rest', tags:['dfs','bfs','matrix'] },
            { id:'gb-012', name:'Network Delay Time', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/network-delay-time/', hint:'Dijkstra from k. Track shortest distances. Return max of distances.', trigger:'When you see: shortest path weighted graph -> Dijkstra with min-heap', tags:['dijkstra','heap','graph'] }
          ]
        },
        {
          id: 'advanced-graphs',
          name: 'Advanced Graphs',
          problems: [
            { id:'ag-001', name:'Course Schedule II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/course-schedule-ii/', hint:"Topological sort (Kahn's): track in-degrees, add 0-in-degree to queue, process.", trigger:"When you see: ordering with dependencies -> Topological sort (Kahn's BFS or DFS postorder)", tags:['topological-sort','dfs','bfs','graph'] },
            { id:'ag-002', name:'Alien Dictionary', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/alien-dictionary/', hint:'Compare adjacent words to extract ordering. Topological sort char graph. Cycle = "".', trigger:'When you see: deduce char order from sorted words -> Build char-order graph + topo sort', tags:['topological-sort','graph','bfs','dfs'] },
            { id:'ag-003', name:'Cheapest Flights Within K Stops', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/cheapest-flights-within-k-stops/', hint:'Bellman-Ford k+1 iterations. Or BFS/Dijkstra with state (cost, node, stops).', trigger:'When you see: shortest path with limited hops -> Bellman-Ford k iterations', tags:['dynamic-programming','dijkstra','graph'] },
            { id:'ag-004', name:'Word Ladder', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/word-ladder/', hint:'BFS: each word is node, edge if 1 char different. Shortest path from begin to end.', trigger:'When you see: minimum transformation steps, 1 char diff -> BFS on word graph', tags:['bfs','graph','hash-set'] },
            { id:'ag-005', name:'Reconstruct Itinerary', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/reconstruct-itinerary/', hint:"Hierholzer's algorithm. Sorted adjacency. DFS: push to result after neighbors exhausted.", trigger:"When you see: Eulerian path/circuit -> Hierholzer's DFS, post-order reversal", tags:['dfs','graph'] },
            { id:'ag-006', name:'Critical Connections in a Network', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/critical-connections-in-a-network/', hint:"Tarjan's bridge-finding. Edge (u,v) is bridge if low[v] > disc[u].", trigger:"When you see: find bridges -> Tarjan's (disc time + low value)", tags:['dfs','graph','tarjan'] },
            { id:'ag-007', name:'Min Cost to Connect All Points', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/min-cost-to-connect-all-points/', hint:"MST with Prim's or Kruskal's. All pairs have Manhattan distance edges.", trigger:"When you see: minimum cost connect all nodes -> MST (Prim's or Kruskal's)", tags:['graph','mst','prim','kruskal'] },
            { id:'ag-008', name:'Accounts Merge', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/accounts-merge/', hint:'Union-Find all emails per account. Group by root. Sort emails.', trigger:'When you see: merge overlapping groups by common element -> Union-Find on shared elements', tags:['union-find','dfs','graph'] },
            { id:'ag-009', name:'Number of Provinces', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/number-of-provinces/', hint:'DFS/BFS or Union-Find on adjacency matrix. Count components.', trigger:'When you see: count groups in adjacency matrix -> DFS or Union-Find', tags:['dfs','bfs','union-find','graph'] },
            { id:'ag-010', name:'Redundant Connection', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/redundant-connection/', hint:'Union-Find. Edge connecting already-connected nodes is redundant.', trigger:'When you see: edge creating cycle -> Union-Find, return first edge both already connected', tags:['union-find','dfs','graph'] }
          ]
        }
      ]
    },
    {
      id: 'dynamic-programming',
      name: 'Dynamic Programming',
      subtopics: [
        {
          id: '1d-dp',
          name: '1D DP',
          problems: [
            { id:'dp1-001', name:'Climbing Stairs', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/climbing-stairs/', hint:'dp[i] = dp[i-1] + dp[i-2]. Fibonacci.', trigger:'When you see: ways to climb 1 or 2 steps -> Fibonacci DP', tags:['dynamic-programming','math'] },
            { id:'dp1-002', name:'House Robber', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/house-robber/', hint:'dp[i] = max(dp[i-1], dp[i-2]+nums[i]).', trigger:'When you see: max sum no two adjacent -> dp[i] = max(skip, rob)', tags:['dynamic-programming','array'] },
            { id:'dp1-003', name:'House Robber II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/house-robber-ii/', hint:'Run House Robber on [0..n-2] and [1..n-1]. Take max.', trigger:'When you see: house robber circular -> Linear HouseRobber on both halves', tags:['dynamic-programming','array'] },
            { id:'dp1-004', name:'Coin Change', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/coin-change/', hint:'dp[i] = min coins for amount i. For each coin: dp[i] = min(dp[i], dp[i-coin]+1).', trigger:'When you see: minimum coins for amount -> Unbounded knapsack DP', tags:['dynamic-programming','bfs','array'] },
            { id:'dp1-005', name:'Longest Increasing Subsequence', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-increasing-subsequence/', hint:'dp[i] = max(dp[j]+1) for j < i where nums[j] < nums[i]. O(n log n) with binary search.', trigger:'When you see: longest increasing subsequence -> DP O(n^2) or patience sorting O(n log n)', tags:['dynamic-programming','binary-search','array'] },
            { id:'dp1-006', name:'Word Break', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/word-break/', hint:'dp[i] = true if s[0..i] segmentable. Check all j < i where dp[j] && s[j..i] in dict.', trigger:'When you see: segment string into dict words -> DP with dict set', tags:['dynamic-programming','hash-set'] },
            { id:'dp1-007', name:'Partition Equal Subset Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/partition-equal-subset-sum/', hint:'Find subset with sum = total/2. 0/1 knapsack: dp[j] = dp[j] || dp[j-num].', trigger:'When you see: partition into equal subsets -> 0/1 knapsack targeting sum/2', tags:['dynamic-programming','array'] },
            { id:'dp1-008', name:'Target Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/target-sum/', hint:'Count subsets with sum = (total+target)/2. dp[j] += dp[j-num].', trigger:'When you see: assign +/- to reach target -> Count-subset DP', tags:['dynamic-programming','dfs','array'] },
            { id:'dp1-009', name:'Decode Ways', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/decode-ways/', hint:'dp[i]: if s[i-1] valid += dp[i-1]. If s[i-2..i-1] valid (10-26) += dp[i-2].', trigger:'When you see: decode number string to letters -> DP check 1-digit and 2-digit decode', tags:['dynamic-programming','string'] },
            { id:'dp1-010', name:'Jump Game', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/jump-game/', hint:'Track maxReach. If i > maxReach, stuck. Update maxReach = max(maxReach, i+nums[i]).', trigger:'When you see: can we reach end with jumps -> Greedy max-reach tracker', tags:['dynamic-programming','greedy','array'] },
            { id:'dp1-011', name:'Jump Game II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/jump-game-ii/', hint:'Greedy BFS: track currentEnd and farthest. Increment jumps when reaching level end.', trigger:'When you see: minimum jumps to end -> Greedy BFS, count levels', tags:['dynamic-programming','greedy','array'] },
            { id:'dp1-012', name:'Maximum Product Subarray', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/maximum-product-subarray/', hint:'Track both maxProd and minProd. Negative flips max/min.', trigger:'When you see: max product subarray -> Track both maxProd and minProd', tags:['dynamic-programming','array'] }
          ]
        },
        {
          id: '2d-dp',
          name: '2D DP',
          problems: [
            { id:'dp2-001', name:'Unique Paths', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/unique-paths/', hint:'dp[i][j] = dp[i-1][j] + dp[i][j-1].', trigger:'When you see: count paths moving right/down -> 2D DP sum from top and left', tags:['dynamic-programming','math'] },
            { id:'dp2-002', name:'Minimum Path Sum', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/minimum-path-sum/', hint:'dp[i][j] = grid[i][j] + min(dp[i-1][j], dp[i][j-1]).', trigger:'When you see: minimum cost path in grid -> 2D DP min from top or left', tags:['dynamic-programming','array','matrix'] },
            { id:'dp2-003', name:'Edit Distance', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/edit-distance/', hint:'dp[i][j]: chars match->dp[i-1][j-1]. Else 1+min(insert,delete,replace).', trigger:'When you see: min operations string to string -> Edit distance DP (Levenshtein)', tags:['dynamic-programming','string'] },
            { id:'dp2-004', name:'Longest Common Subsequence', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/longest-common-subsequence/', hint:'Match: 1+dp[i-1][j-1]. Else max(dp[i-1][j], dp[i][j-1]).', trigger:'When you see: longest common subsequence -> 2D DP match/skip', tags:['dynamic-programming','string'] },
            { id:'dp2-005', name:'Best Time to Buy and Sell Stock with Cooldown', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', hint:'Three states: held=max(held, rest-price), sold=held+price, rest=max(rest,sold).', trigger:'When you see: stock with cooldown -> State machine DP (held, sold, rest)', tags:['dynamic-programming','array'] },
            { id:'dp2-006', name:'Interleaving String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/interleaving-string/', hint:'dp[i][j] = can s1[0..i-1] and s2[0..j-1] form s3[0..i+j-1].', trigger:'When you see: two strings interleave to form third -> 2D DP tracking both positions', tags:['dynamic-programming','string'] },
            { id:'dp2-007', name:'Regular Expression Matching', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/regular-expression-matching/', hint:"If p[j]='*': zero occurrences (dp[i][j-2]) or one+ (dp[i-1][j] if match).", trigger:"When you see: regex with . and * -> 2D DP, * = zero or more previous char", tags:['dynamic-programming','recursion','string'] },
            { id:'dp2-008', name:'Wildcard Matching', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/wildcard-matching/', hint:"If p[j]='*': dp[i][j-1] (ignore) or dp[i-1][j] (match one more s char).", trigger:"When you see: wildcard with ? and * -> 2D DP, * = empty OR match one more", tags:['dynamic-programming','recursion','string'] },
            { id:'dp2-009', name:'Maximal Square', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/maximal-square/', hint:'dp[i][j] = 1 + min(top, left, diag) if matrix[i][j]=1.', trigger:'When you see: largest square of 1s -> dp[i][j] = 1 + min(top, left, diag)', tags:['dynamic-programming','matrix'] },
            { id:'dp2-010', name:'Cherry Pickup', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/cherry-pickup/', hint:'Two simultaneous paths. dp[step][r1][r2] since step = r1+c1 = r2+c2.', trigger:'When you see: two paths through grid -> 3D DP same step count', tags:['dynamic-programming','matrix'] }
          ]
        }
      ]
    },
    {
      id: 'binary-search',
      name: 'Binary Search',
      subtopics: [
        {
          id: 'binary-search-patterns',
          name: 'Binary Search Patterns',
          problems: [
            { id:'bsrch-001', name:'Binary Search', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/binary-search/', hint:'left=0, right=n-1. mid=(l+r)//2. Compare and narrow.', trigger:'When you see: find element in sorted array -> Binary search O(log n)', tags:['binary-search','array'] },
            { id:'bsrch-002', name:'Search Insert Position', difficulty:'Easy', platform:'leetcode', url:'https://leetcode.com/problems/search-insert-position/', hint:'Binary search. Left pointer is insert position when not found.', trigger:'When you see: find insert position in sorted array -> Binary search, return left', tags:['binary-search','array'] },
            { id:'bsrch-003', name:'Find Minimum in Rotated Sorted Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', hint:'If nums[mid] > nums[right], minimum is in right half. Else in left (including mid).', trigger:'When you see: minimum in rotated array -> Compare mid with right', tags:['binary-search','array'] },
            { id:'bsrch-004', name:'Search in Rotated Sorted Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/search-in-rotated-sorted-array/', hint:'One half always sorted. Check if target in sorted half, narrow search.', trigger:'When you see: search in rotated array -> Determine sorted half, check target', tags:['binary-search','array'] },
            { id:'bsrch-005', name:'Find Peak Element', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/find-peak-element/', hint:'If nums[mid] < nums[mid+1], peak on right. Else on left including mid.', trigger:'When you see: find local maximum -> Binary search on slope direction', tags:['binary-search','array'] },
            { id:'bsrch-006', name:'Koko Eating Bananas', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/koko-eating-bananas/', hint:'Binary search speed 1..max. For each k, compute hours. Find min k where hours <= h.', trigger:'When you see: minimize rate with feasibility check -> Binary search on answer', tags:['binary-search','array'] },
            { id:'bsrch-007', name:'Capacity To Ship Packages Within D Days', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', hint:'Binary search on capacity. Greedily simulate, check if done in D days.', trigger:'When you see: minimum capacity with days constraint -> Binary search + greedy feasibility', tags:['binary-search','array','greedy'] },
            { id:'bsrch-008', name:'Split Array Largest Sum', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/split-array-largest-sum/', hint:'Binary search on answer. Check if can split into m parts with sum <= mid.', trigger:'When you see: minimize maximum partition sum -> Binary search on answer + greedy split', tags:['binary-search','dynamic-programming','greedy'] },
            { id:'bsrch-009', name:'Search a 2D Matrix', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/search-a-2d-matrix/', hint:'Treat as flat sorted array. row=mid/cols, col=mid%cols.', trigger:'When you see: search row-sorted matrix -> Treat as 1D, map mid to (row,col)', tags:['binary-search','matrix','array'] },
            { id:'bsrch-010', name:'Time Based Key-Value Store', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/time-based-key-value-store/', hint:'List of (timestamp, value) per key. Binary search for largest ts <= given.', trigger:'When you see: value at or before timestamp -> Sorted list + binary search', tags:['binary-search','hash-map','design'] },
            { id:'bsrch-011', name:'Median of Two Sorted Arrays', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/median-of-two-sorted-arrays/', hint:'Binary search on smaller array. Partition so all left <= all right.', trigger:'When you see: median of two sorted arrays O(log n) -> Binary search partition', tags:['binary-search','array','divide-and-conquer'] },
            { id:'bsrch-012', name:'Magnetic Force Between Two Balls', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/magnetic-force-between-two-balls/', hint:'Binary search on minimum force. Check if m balls fit with >= mid distance.', trigger:'When you see: maximize minimum distance between placed items -> Binary search on answer', tags:['binary-search','sorting','greedy'] }
          ]
        }
      ]
    },
    {
      id: 'heap',
      name: 'Heap / Priority Queue',
      subtopics: [
        {
          id: 'heap-patterns',
          name: 'Heap Patterns',
          problems: [
            { id:'hp-001', name:'Kth Largest Element in an Array', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/kth-largest-element-in-an-array/', hint:'Min-heap size k. Push each, pop if > k. Root = kth largest.', trigger:'When you see: kth largest/smallest -> Min-heap of size k', tags:['heap','sorting','quickselect'] },
            { id:'hp-002', name:'Top K Frequent Elements', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/top-k-frequent-elements/', hint:'Freq map. Min-heap size k or bucket sort by freq.', trigger:'When you see: top k frequent -> Freq map + min-heap size k', tags:['heap','hash-map','bucket-sort'] },
            { id:'hp-003', name:'Find Median from Data Stream', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/find-median-from-data-stream/', hint:'Two heaps: max-heap lower half, min-heap upper half. Balance sizes. Median from tops.', trigger:'When you see: running median -> Two heaps (max lower, min upper)', tags:['heap','two-pointers','design'] },
            { id:'hp-004', name:'K Closest Points to Origin', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/k-closest-points-to-origin/', hint:'Max-heap size k. Pop farthest when > k. Remaining = k closest.', trigger:'When you see: k closest points -> Max-heap size k', tags:['heap','sorting','divide-and-conquer'] },
            { id:'hp-005', name:'Task Scheduler', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/task-scheduler/', hint:'Max-heap by freq. Execute most frequent. Cool-down tasks wait.', trigger:'When you see: schedule tasks with cooling -> Max-heap by freq + cooling queue', tags:['heap','greedy','hash-map'] },
            { id:'hp-006', name:'Ugly Number II', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/ugly-number-ii/', hint:'DP: ugly[i] = min(ugly[p2]*2, ugly[p3]*3, ugly[p5]*5). Advance used pointer.', trigger:'When you see: nth number with prime factors 2,3,5 -> Three-pointer DP', tags:['heap','dynamic-programming','math'] },
            { id:'hp-007', name:'Reorganize String', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/reorganize-string/', hint:'Max-heap by freq. Place most frequent, wait one step, re-add.', trigger:'When you see: rearrange no two adjacent same -> Max-heap greedy with gap', tags:['heap','greedy','hash-map','string'] },
            { id:'hp-008', name:'Merge k Sorted Lists', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/merge-k-sorted-lists/', hint:'Min-heap (val, listIdx, node). Extract min, push next.', trigger:'When you see: merge k sorted lists -> Min-heap one element per list', tags:['heap','linked-list','divide-and-conquer'] },
            { id:'hp-009', name:'Kth Smallest Element in a Sorted Matrix', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/', hint:'Min-heap: first element each row. Pop k-1 times, push next in row.', trigger:'When you see: kth smallest in sorted matrix -> Min-heap, one element per row', tags:['heap','binary-search','matrix'] },
            { id:'hp-010', name:'Smallest Number in Infinite Set', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/smallest-number-in-infinite-set/', hint:'Track pointer + min-heap for re-added elements. PopSmallest = min(heap.top, pointer).', trigger:'When you see: infinite set with add-back -> Pointer + min-heap for re-added', tags:['heap','hash-set','design'] },
            { id:'hp-011', name:'Design Twitter', difficulty:'Medium', platform:'leetcode', url:'https://leetcode.com/problems/design-twitter/', hint:'Per-user tweet list. Feed: collect from followed users, max-heap for top 10.', trigger:'When you see: merge recent posts from multiple sources -> Per-user lists + max-heap', tags:['heap','hash-map','design'] },
            { id:'hp-012', name:'IPO', difficulty:'Hard', platform:'leetcode', url:'https://leetcode.com/problems/ipo/', hint:'Sort by capital. Max-heap of profits. Add affordable projects, pick most profitable k times.', trigger:'When you see: pick k most profitable affordable projects -> Sort by cost + max-heap profits', tags:['heap','greedy','sorting'] }
          ]
        }
      ]
    }
  ],

  codeforces: {
    problems: [
      { id:'cf-001', name:'Watermelon', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/4/A', hint:'Check if n is even and n > 2. Both parts must be even.', trigger:'When you see: split into two even parts -> Check n is even and >= 4', tags:['math','brute-force'], rating:800 },
      { id:'cf-002', name:'Way Too Long Words', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/71/A', hint:'If length <= 10 keep. Else: first_char + (length-2) + last_char.', trigger:'When you see: abbreviate long words -> first + middle_count + last', tags:['strings','implementation'], rating:800 },
      { id:'cf-003', name:'Team', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/231/A', hint:'For each problem, sum votes. If >= 2, count as solved.', trigger:'When you see: majority vote per item -> Sum votes, check >= threshold', tags:['greedy','implementation'], rating:800 },
      { id:'cf-004', name:'Bit++', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/282/A', hint:'Contains "++" increment X, else decrement.', trigger:'When you see: parse increment/decrement ops -> Check "++" or "--" in string', tags:['implementation'], rating:800 },
      { id:'cf-005', name:'Theatre Square', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/1/A', hint:'Tiles = ceil(n/a) * ceil(m/a). Use (n+a-1)/a for ceiling.', trigger:'When you see: cover area with square tiles -> ceil(rows/tile) * ceil(cols/tile)', tags:['math','implementation'], rating:1000 },
      { id:'cf-006', name:'Next Round', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/158/A', hint:'Find kth score (threshold). Count with score >= threshold AND > 0.', trigger:'When you see: pass if score >= kth and > 0 -> Filter by both conditions', tags:['implementation','sortings'], rating:900 },
      { id:'cf-007', name:'Boy or Girl', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/236/A', hint:'Count distinct chars. Odd = boy, even = girl.', trigger:'When you see: determine from distinct char count -> Odd=boy, even=girl', tags:['strings','implementation'], rating:800 },
      { id:'cf-008', name:'Tram', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/116/A', hint:'Track running passengers count. Find maximum.', trigger:'When you see: minimum tram capacity -> Track running passengers, find max', tags:['implementation'], rating:1200 },
      { id:'cf-009', name:'Soldier and Bananas', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/546/A', hint:'Total cost = k*(k+1)/2. Deficit = cost - money (if positive), else 0.', trigger:'When you see: arithmetic sum vs budget -> k*(k+1)/2, check deficit', tags:['math','implementation'], rating:1100 },
      { id:'cf-010', name:'Vanya and Fence', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/677/A', hint:'Adults (2m) pass alone. Children (1m) need pairs to pass 2m fence.', trigger:'When you see: pair shorter items to pass height -> Count pairs, compute groups', tags:['greedy','implementation'], rating:1200 },
      { id:'cf-011', name:'Queue at the School', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/266/B', hint:'Simulate t seconds. Each second B swaps with adjacent G behind it.', trigger:'When you see: simulate queue boys past girls -> Simulate each second', tags:['implementation','simulation'], rating:1200 },
      { id:'cf-012', name:'Divisibility Problem', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/1209/A', hint:'To make a divisible by b: add (b - a%b) % b.', trigger:'When you see: minimum add to make divisible -> (b - a%b) % b', tags:['math','implementation'], rating:800 },
      { id:'cf-013', name:'Lucky Division', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/121/A', hint:'Lucky numbers have only digits 4 and 7. Generate all up to n. Check divisors.', trigger:'When you see: lucky number (4s and 7s) divisors -> Generate all, check which divide n', tags:['math','brute-force'], rating:1200 },
      { id:'cf-014', name:'Young Physicist', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/68/A', hint:'Sum all vectors. If (0,0,0), balanced.', trigger:'When you see: check if vectors sum to zero -> Add x,y,z separately', tags:['math','implementation'], rating:1200 },
      { id:'cf-015', name:'Twins', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/160/A', hint:'Sort descending. Greedily take largest until sum > total/2.', trigger:'When you see: minimum coins majority of total -> Sort desc, greedy accumulate', tags:['greedy','sortings'], rating:1200 },
      { id:'cf-016', name:'Helpful Maths', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/339/A', hint:'Parse all numbers from expression, sort, join with + signs.', trigger:'When you see: sort summands in expression -> Parse, sort, reassemble with +', tags:['strings','sortings','implementation'], rating:1200 },
      { id:'cf-017', name:'Vasya the Hipster', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/390/A', hint:'Mixed pairs = min(a,b). Remaining = (a-min + b-min)/2 single-color pairs.', trigger:'When you see: pair different then same colored socks -> min(a,b) mixed, floor(rem/2) same', tags:['math','greedy'], rating:1300 },
      { id:'cf-018', name:'Pangram', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/520/A', hint:'Collect distinct lowercase letters. Count == 26 means pangram.', trigger:'When you see: check all letters present -> Set of lowercase, size == 26', tags:['strings','implementation'], rating:1000 },
      { id:'cf-019', name:'Magnets', difficulty:'Medium', url:'https://codeforces.com/problemset/problem/344/A', hint:'Count transitions between NN and SS pairs (direction changes).', trigger:'When you see: count direction changes in sequence -> Count adjacent transitions', tags:['implementation'], rating:1000 },
      { id:'cf-020', name:'Beautiful Matrix', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/271/A', hint:'Find 5 in matrix. Swaps = |row-2| + |col-2| to move to center.', trigger:'When you see: move element to center minimum swaps -> Manhattan distance to center', tags:['implementation','sortings'], rating:1200 },
      { id:'cf-021', name:'Kefa and First Steps', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/580/A', hint:'Sliding window: longest subarray with at most 1 distinct char.', trigger:'When you see: longest subarray at most 1 distinct char -> Sliding window', tags:['implementation','strings'], rating:1400 },
      { id:'cf-022', name:'Sereja and Dima', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/380/B', hint:'Two greedy pointers. Each player takes larger of two ends. Alternate.', trigger:'When you see: two players pick from ends greedily -> Two pointers, pick max end', tags:['greedy','two-pointers'], rating:1600 },
      { id:'cf-023', name:'A Lot of Games', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/455/B', hint:'DP on trie: track canWin and canLose per state. n rounds.', trigger:'When you see: string game on trie n rounds -> DP tracking win/lose per round', tags:['trie','dynamic-programming','game-theory'], rating:1500 },
      { id:'cf-024', name:'Towers', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/479/B', hint:'Find max and min towers. Transfer blocks from max to min. Minimize diff.', trigger:'When you see: equalize towers minimize difference -> Find min/max, transfer', tags:['greedy','implementation'], rating:1300 },
      { id:'cf-025', name:'Boredom', difficulty:'Hard', url:'https://codeforces.com/problemset/problem/455/A', hint:'Like House Robber: dp[i] = max(dp[i-1], dp[i-2] + i*count[i]).', trigger:'When you see: select values but cannot pick adjacent -> House Robber DP on frequency', tags:['dynamic-programming'], rating:1500 }
    ],
    contests: []
  }
};
