/* ================================================================
   RESEARCH TRACKER INITIAL SEED DATA
   ================================================================ */
const RESEARCH_DATA = [
  {
    id: "res-1",
    title: "Attention Is All You Need",
    area: "Natural Language Processing",
    type: "Paper",
    status: "Read",
    authors: "Vaswani et al.",
    source: "NeurIPS 2017",
    url: "https://arxiv.org/abs/1706.03762",
    dataset: "WMT 2014 English-to-German / English-to-French",
    methodology: "Replaced recurrence and convolutions entirely with multi-head self-attention mechanisms and positional encoding.",
    model: "Transformer (Encoder-Decoder)",
    key_findings: "Achieved state-of-the-art BLEU scores (28.4 En-De) with significantly faster training time and full parallelization.",
    limitations: "Quadratic computational and memory complexity with respect to sequence length.",
    research_gap: "Efficient sub-quadratic attention for ultra-long context windows (>100k tokens).",
    useful_notes: "Seminal paper that powers modern LLMs (BERT, GPT, Claude, Gemini, LLaMA).",
    ideas: "Explore linear attention approximations and state space models (Mamba) for linear scaling.",
    recommendations: "Must read for anyone working with modern deep learning and LLM architectures.",
    priority: "High",
    tags: ["transformers", "attention", "nlp", "llm"],
    archived: false,
    dateAdded: Date.now() - 86400000 * 14
  },
  {
    id: "res-2",
    title: "Spanner: Google's Globally-Distributed Database",
    area: "Distributed Systems",
    type: "Paper",
    status: "Summarized",
    authors: "Corbett et al. (Google)",
    source: "OSDI 2012",
    url: "https://research.google/pubs/pub39966/",
    dataset: "Google internal production workloads (F1 advertisement backend)",
    methodology: "Hardware-assisted time synchronization using GPS and atomic clocks (TrueTime API) to provide external consistency without central coordination.",
    model: "Multi-version distributed SQL database with Paxos replication and 2-phase commit.",
    key_findings: "Proves that with bounded clock uncertainty, distributed transactions can achieve linearizability across global data centers.",
    limitations: "Requires specialized atomic clock and GPS hardware receivers in data centers.",
    research_gap: "Pure software-based global ordering with minimal latency overhead on commodity cloud hardware.",
    useful_notes: "Core inspiration for modern distributed SQL engines like CockroachDB and YugabyteDB.",
    ideas: "Combine hybrid logical clocks (HLC) with Raft consensus for cost-effective multi-cloud replication.",
    recommendations: "Essential reading for system design interviews and distributed consistency deep-dives.",
    priority: "High",
    tags: ["distributed-systems", "databases", "consensus", "paxos", "truetime"],
    archived: false,
    dateAdded: Date.now() - 86400000 * 7
  },
  {
    id: "res-3",
    title: "RAFT: In Search of an Understandable Consensus Algorithm",
    area: "Distributed Systems",
    type: "Paper",
    status: "Implemented",
    authors: "Ongaro & Ousterhout (Stanford)",
    source: "USENIX ATC 2014",
    url: "https://raft.github.io/raft.pdf",
    dataset: "User study with 43 students across Stanford and UC Berkeley",
    methodology: "Decomposed state machine consensus into three independent subproblems: Leader Election, Log Replication, and Safety.",
    model: "Leader-based Consensus State Machine",
    key_findings: "Provides equivalent safety and efficiency to Multi-Paxos while being dramatically simpler to understand, implement, and formally verify.",
    limitations: "Leader bottleneck under write-heavy workloads; single leader failover latency requires heartbeat timeouts.",
    research_gap: "Multi-leader consensus and Byzantine fault-tolerant extensions (e.g. Tendermint, HotStuff).",
    useful_notes: "Used in etcd (Kubernetes), HashiCorp Consul, TiKV, and modern cloud native infra.",
    ideas: "Implement a toy Raft cluster in Go / TypeScript to master consensus edge cases.",
    recommendations: "Great starting point for distributed consensus before tackling Paxos.",
    priority: "Medium",
    tags: ["raft", "consensus", "distributed-systems", "fault-tolerance"],
    archived: false,
    dateAdded: Date.now() - 86400000 * 3
  }
];
